
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"17",
  "macros":[{
      "function":"__e"
    },{
      "function":"__u",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__e"
    },{
      "function":"__u",
      "vtp_component":"URL",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"HOST",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"PATH",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__f",
      "vtp_component":"URL"
    }],
  "tags":[{
      "function":"__awct",
      "once_per_event":true,
      "vtp_enableConversionLinker":true,
      "vtp_conversionCookiePrefix":"_gcl",
      "vtp_conversionId":"1012071701",
      "vtp_conversionLabel":"DuHnCKqtnnsQlfrL4gM",
      "vtp_url":["macro",1],
      "vtp_enableProductReportingCheckbox":false,
      "vtp_enableEnhancedConversionsCheckbox":false,
      "tag_id":1
    },{
      "function":"__twitter_website_tag",
      "once_per_event":true,
      "vtp_event_type":"PageView",
      "vtp_twitter_pixel_id":"l6rir",
      "tag_id":2
    },{
      "function":"__cegg",
      "once_per_event":true,
      "vtp_usersNumericId":"00585570",
      "tag_id":3
    },{
      "function":"__gclidw",
      "once_per_event":true,
      "vtp_enableCookieOverrides":false,
      "vtp_enableCrossDomainFeature":true,
      "vtp_enableCookieUpdateFeature":false,
      "tag_id":5
    },{
      "function":"__twitter_website_tag",
      "once_per_event":true,
      "vtp_event_type":"Purchase",
      "vtp_twitter_pixel_id":"nzcme",
      "tag_id":6
    },{
      "function":"__ga",
      "once_per_event":true,
      "vtp_detectTitle":true,
      "vtp_ignoredRef":["list"],
      "vtp_useDebugVersion":false,
      "vtp_allowLinker":false,
      "vtp_trackType":"TRACK_TRANSACTION",
      "vtp_cookiePathCopy":["list"],
      "vtp_clientInfo":true,
      "vtp_campaignTrack":true,
      "vtp_anonymizeIp":false,
      "vtp_webPropertyId":"UA-13798657-0",
      "vtp_allowAnchor":false,
      "vtp_allowHash":true,
      "vtp_doubleClick":false,
      "vtp_setTrackerName":false,
      "vtp_sendHitsToGoogle":true,
      "vtp_enableInPageLinkId":false,
      "vtp_forceSsl":false,
      "vtp_ignoredOrganic":["list"],
      "vtp_detectFlash":true,
      "vtp_trackTypeIsTransaction":true,
      "tag_id":12
    },{
      "function":"__baut",
      "once_per_event":true,
      "vtp_tagId":"25025042",
      "vtp_uetqName":"uetq",
      "vtp_eventType":"PAGE_LOAD",
      "tag_id":13
    },{
      "function":"__baut",
      "once_per_event":true,
      "vtp_tagId":"25025042",
      "vtp_uetqName":"uetq",
      "vtp_eventType":"CUSTOM",
      "vtp_eventAction":"freeTrialStart",
      "tag_id":14
    },{
      "function":"__pntr",
      "once_per_event":true,
      "vtp_setCustomParams":false,
      "vtp_tagId":"2614876804407",
      "vtp_eventName":"pagevisit",
      "tag_id":16
    },{
      "function":"__pntr",
      "once_per_event":true,
      "vtp_setCustomParams":false,
      "vtp_tagId":"2614876804407",
      "vtp_eventName":"signup",
      "vtp_lead_type":["macro",2],
      "tag_id":17
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\n\n\u003Cscript type=\"text\/gtmscript\"\u003E!function(d,e,f,a,b,c){d.qp||(a=d.qp=function(){a.qp?a.qp.apply(a,arguments):a.queue.push(arguments)},a.queue=[],b=document.createElement(e),b.async=!0,b.src=f,c=document.getElementsByTagName(e)[0],c.parentNode.insertBefore(b,c))}(window,\"script\",\"https:\/\/a.quora.com\/qevents.js\");qp(\"init\",\"ac4eee574a084aadb64bfbe6f182a659\");qp(\"track\",\"ViewContent\");\u003C\/script\u003E\n\u003Cnoscript\u003E\u003Cimg height=\"1\" width=\"1\" style=\"display:none\" src=\"https:\/\/q.quora.com\/_\/ad\/ac4eee574a084aadb64bfbe6f182a659\/pixel?tag=ViewContent\u0026amp;noscript=1\"\u003E\u003C\/noscript\u003E\n\u003Cscript type=\"text\/gtmscript\"\u003Eqp(\"track\",\"Generic\");\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":4
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\n\u003Cscript type=\"text\/gtmscript\"\u003Evar _qevents=_qevents||[];(function(){var a=document.createElement(\"script\");a.src=(\"https:\"==document.location.protocol?\"https:\/\/secure\":\"http:\/\/edge\")+\".quantserve.com\/quant.js\";a.async=!0;a.type=\"text\/javascript\";var b=document.getElementsByTagName(\"script\")[0];b.parentNode.insertBefore(a,b)})();_qevents.push({qacct:\"p-ZX0Yrb3eefUKS\"});\u003C\/script\u003E\n\u003Cnoscript\u003E\n \u003Cimg src=\"\/\/pixel.quantserve.com\/pixel\/p-ZX0Yrb3eefUKS.gif?labels=_fp.event.Default\" style=\"display: none;\" border=\"0\" height=\"1\" width=\"1\" alt=\"Quantcast\"\u003E\n\u003C\/noscript\u003E\n",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":7
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\n\u003Cscript type=\"text\/gtmscript\"\u003Evar _qevents=_qevents||[];(function(){var a=document.createElement(\"script\");a.src=(\"https:\"==document.location.protocol?\"https:\/\/secure\":\"http:\/\/edge\")+\".quantserve.com\/quant.js\";a.async=!0;a.type=\"text\/javascript\";var b=document.getElementsByTagName(\"script\")[0];b.parentNode.insertBefore(a,b)})();_qevents.push({qacct:\"p-ZX0Yrb3eefUKS\",labels:\"_fp.event.Free Trial Confirmation\",orderid:\"INSERT+ORDER+ID\",event:\"refresh\"});\u003C\/script\u003E\n\u003Cnoscript\u003E\n\u003Cimg src=\"\/\/pixel.quantserve.com\/pixel\/p-ZX0Yrb3eefUKS.gif?labels=_fp.event.Free+Trial+Confirmation\u0026amp;orderid=INSERT+ORDER+ID\" style=\"display: none;\" border=\"0\" height=\"1\" width=\"1\" alt=\"Quantcast\"\u003E\n\u003C\/noscript\u003E\n",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":8
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\n\n\u003Cscript type=\"text\/gtmscript\"\u003E!function(d,e,f,a,b,c){d.qp||(a=d.qp=function(){a.qp?a.qp.apply(a,arguments):a.queue.push(arguments)},a.queue=[],b=document.createElement(e),b.async=!0,b.src=f,c=document.getElementsByTagName(e)[0],c.parentNode.insertBefore(b,c))}(window,\"script\",\"https:\/\/a.quora.com\/qevents.js\");qp(\"init\",\"ac4eee574a084aadb64bfbe6f182a659\");qp(\"track\",\"ViewContent\");\u003C\/script\u003E\n\u003Cnoscript\u003E\u003Cimg height=\"1\" width=\"1\" style=\"display:none\" src=\"https:\/\/q.quora.com\/_\/ad\/ac4eee574a084aadb64bfbe6f182a659\/pixel?tag=ViewContent\u0026amp;noscript=1\"\u003E\u003C\/noscript\u003E\n\u003Cscript type=\"text\/gtmscript\"\u003Eqp(\"track\",\"Purchase\");\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":9
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003Ewindow._tfa=window._tfa||[];window._tfa.push({notify:\"event\",name:\"page_view\"});!function(a,b,d,c){document.getElementById(c)||(a.async=1,a.src=d,a.id=c,b.parentNode.insertBefore(a,b))}(document.createElement(\"script\"),document.getElementsByTagName(\"script\")[0],\"\/\/cdn.taboola.com\/libtrc\/unip\/1144369\/tfa.js\",\"tb_tfa_script\");\u003C\/script\u003E\n\u003Cnoscript\u003E\n  \u003Cimg src=\"\/\/trc.taboola.com\/1144369\/log\/3\/unip?en=page_view\" width=\"0\" height=\"0\" style=\"display:none\"\u003E\n\u003C\/noscript\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":10
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003E_tfa.push({notify:\"event\",name:\"taboola_ft_purchase\"});\u003C\/script\u003E\n\u003Cnoscript\u003E\n    \u003Cimg src=\"\/\/trc.taboola.com\/1144369\/log\/3\/unip?en=taboola_ft_purchase\" width=\"0\" height=\"0\" style=\"display:none\"\u003E\n\u003C\/noscript\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":11
    },{
      "function":"__html",
      "once_per_load":true,
      "vtp_html":"\n\u003Cscript type=\"text\/gtmscript\"\u003E!function(b,c){if(!b.pixie){var d=b.pixie=function(a,b,c){d.actionQueue.push({action:a,actionValue:b,params:c})};d.actionQueue=[];var a=c.createElement(\"script\");a.async=!0;a.src=\"\/\/acdn.adnxs.com\/dmp\/up\/pixie.js\";var e=c.getElementsByTagName(\"head\")[0];e.insertBefore(a,e.firstChild)}}(window,document);pixie(\"init\",\"14920b18-91b2-4993-b111-3b2b5ca1d6bb\");pixie(\"event\",\"PageView\");\u003C\/script\u003E \n\u003Cnoscript\u003E\u003Cimg width=\"1\" height=\"1\" style=\"display:none;\" src=\"\/\/px.adnxs.com\/pixie?pi=14920b18-91b2-4993-b111-3b2b5ca1d6bb\u0026amp;e=PageView\u0026amp;script=0\"\u003E\u003C\/noscript\u003E\n\n",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":18
    }],
  "predicates":[{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"freeTrialStart"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.js"
    }],
  "rules":[
    [["if",0],["add",0,4,5,7,9,12,13,15],["block",11]],
    [["if",1],["add",1,2,3,6,8,10,11,14,16]]]
},
"runtime":[
[],[50,"__pntr",[46,"a"],[52,"b",["require","copyFromWindow"]],[52,"c",["require","createArgumentsQueue"]],[52,"d",["require","injectScript"]],[52,"e",["require","logToConsole"]],[52,"f",["require","makeTableMap"]],["e",[0,"Pinterest tagId: ",[17,[15,"a"],"tagId"]]],[52,"g",[28,["b","pintrk"]]],[52,"h",["c","pintrk","pintrk.queue"]],[22,[15,"g"],[46,[53,[52,"k",[8,"np","gtm"]],[22,[17,[15,"a"],"em"],[46,[43,[15,"k"],"em",[17,[15,"a"],"em"]]]],["h","load",[2,[17,[15,"a"],"tagId"],"toString",[7]],[15,"k"]],["h","page",[15,"k"]]]]],[52,"i",[51,"",[7],["e",[0,"Firing Pinterest event: ",[17,[15,"a"],"eventName"]]],[41,"k"],[3,"k",[8]],[22,[17,[15,"a"],"setCustomParams"],[46,[3,"k",["f",[17,[15,"a"],"values"],"name","value"]]]],[43,[15,"k"],"np","gtm"],[52,"l",[51,"",[7,"m"],[22,[21,[16,[15,"a"],[15,"m"]],[44]],[46,[43,[15,"k"],[15,"m"],[16,[15,"a"],[15,"m"]]]]]]],[38,[17,[15,"a"],"eventName"],[46,"pagevisit","watchvideo","viewcategory","custom","signup","lead","search","addtocart","checkout"],[46,[5,[46]],[5,[46]],[5,[46]],[5,[46,[4]]],[5,[46]],[5,[46,["l","lead_type"],[4]]],[5,[46,["l","search_query"],[4]]],[5,[46]],[5,[46,["l","order_id"],["l","order_quantity"],["l","value"],["l","currency"],["l","product_id"],["l","product_category"],[4]]],[9,[46,[4]]]]],[22,[21,[17,[15,"a"],"pageName"],[44]],[46,[43,[15,"k"],"page_name",[17,[15,"a"],"pageName"]]]],[22,[21,[17,[15,"a"],"pageCategory"],[44]],[46,[43,[15,"k"],"page_catgegory",[17,[15,"a"],"pageCategory"]]]],["h","track",[17,[15,"a"],"eventName"],[15,"k"]],[2,[15,"a"],"gtmOnSuccess",[7]]]],[52,"j",[51,"",[7],["e","Pinterest Error: Loading JS failed!"],[2,[15,"a"],"gtmOnFailure",[7]]]],["d","https://s.pinimg.com/ct/core.js",[15,"i"],[15,"j"],"PinterestJS"]],
[]
]
,"permissions":{"__pntr":{"access_globals":{"keys":[{"key":"pintrk","read":true,"write":true,"execute":true},{"key":"pintrk.queue","read":true,"write":true,"execute":true}]},"logging":{"environments":"debug"},"inject_script":{"urls":["https:\/\/s.pinimg.com\/ct\/core.js"]}},
"null":0}


};
var aa,ca=this||self,da=/^[\w+/_-]+[=]{0,2}$/,ea=null,fa=function(a,b){function c(){}c.prototype=b.prototype;a.ei=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Nh=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var ha=function(a,b){this.K=a;this.eg=b};ha.prototype.sg=function(){return this.K};ha.prototype.getData=function(){return this.eg};ha.prototype.getData=ha.prototype.getData;ha.prototype.getType=ha.prototype.sg;var ia=function(a){return"number"===typeof a&&0<=a&&isFinite(a)&&0===a%1||"string"===typeof a&&"-"!==a[0]&&a===""+parseInt(a,10)},ka=function(){this.F={};this.lb=!1;this.Wc={}};ka.prototype.get=function(a){return this.F["dust."+a]};ka.prototype.set=function(a,b){this.lb||(a="dust."+a,this.Wc.hasOwnProperty(a)||(this.F[a]=b))};ka.prototype.has=function(a){return this.F.hasOwnProperty("dust."+a)};var la=function(a){var b=[],c;for(c in a.F)a.F.hasOwnProperty(c)&&b.push(c.substr(5));return b};
ka.prototype.remove=function(a){a="dust."+a;this.lb||this.Wc.hasOwnProperty(a)||delete this.F[a]};ka.prototype.X=function(){this.lb=!0};var g=function(a){this.Ua=new ka;this.m=[];a=a||[];for(var b in a)a.hasOwnProperty(b)&&(ia(b)?this.m[Number(b)]=a[Number(b)]:this.Ua.set(b,a[b]))};aa=g.prototype;aa.toString=function(){for(var a=[],b=0;b<this.m.length;b++){var c=this.m[b];null===c||void 0===c?a.push(""):a.push(c.toString())}return a.join(",")};aa.set=function(a,b){if("length"==a){if(!ia(b))throw Error("RangeError: Length property must be a valid integer.");this.m.length=Number(b)}else ia(a)?this.m[Number(a)]=b:this.Ua.set(a,b)};
aa.get=function(a){return"length"==a?this.length():ia(a)?this.m[Number(a)]:this.Ua.get(a)};aa.length=function(){return this.m.length};aa.xa=function(){for(var a=la(this.Ua),b=0;b<this.m.length;b++)a.push(b+"");return new g(a)};aa.remove=function(a){ia(a)?delete this.m[Number(a)]:this.Ua.remove(a)};aa.pop=function(){return this.m.pop()};aa.push=function(a){return this.m.push.apply(this.m,Array.prototype.slice.call(arguments))};aa.shift=function(){return this.m.shift()};
aa.splice=function(a,b,c){return new g(this.m.splice.apply(this.m,arguments))};aa.unshift=function(a){return this.m.unshift.apply(this.m,Array.prototype.slice.call(arguments))};aa.has=function(a){return ia(a)&&this.m.hasOwnProperty(a)||this.Ua.has(a)};g.prototype.unshift=g.prototype.unshift;g.prototype.splice=g.prototype.splice;g.prototype.shift=g.prototype.shift;g.prototype.push=g.prototype.push;g.prototype.pop=g.prototype.pop;g.prototype.remove=g.prototype.remove;g.prototype.getKeys=g.prototype.xa;
g.prototype.get=g.prototype.get;g.prototype.set=g.prototype.set;var ma=function(){function a(f,h){if(b[f]){if(b[f].Rb+h>b[f].max)throw Error("Quota exceeded");b[f].Rb+=h}}var b={},c=void 0,d=void 0,e={Pg:function(f){c=f},be:function(){c&&a(c,1)},Qg:function(f){d=f},wa:function(f){d&&a(d,f)},rh:function(f,h){b[f]=b[f]||{Rb:0};b[f].max=h},qg:function(f){return b[f]&&b[f].Rb||0},reset:function(){b={}},Xf:a};e.onFnConsume=e.Pg;e.consumeFn=e.be;e.onStorageConsume=e.Qg;e.consumeStorage=e.wa;e.setMax=e.rh;e.getConsumed=e.qg;e.reset=e.reset;e.consume=e.Xf;return e};var na=function(a,b){this.aa=a;this.bc=function(c,d,e){return c.apply(d,e)};this.Ba=b;this.m=new ka;this.Z=this.Zb=void 0};na.prototype.add=function(a,b){oa(this,a,b,!1)};na.prototype.Lc=function(a,b){oa(this,a,b,!0)};var oa=function(a,b,c,d){if(!a.m.lb)if(a.aa.wa(("string"===typeof b?b.length:1)+("string"===typeof c?c.length:1)),d){var e=a.m;e.set(b,c);e.Wc["dust."+b]=!0}else a.m.set(b,c)};
na.prototype.set=function(a,b){this.m.lb||(this.Ba&&this.Ba.has(a)?this.Ba.set(a,b):(this.aa.wa(("string"===typeof a?a.length:1)+("string"===typeof b?b.length:1)),this.m.set(a,b)))};na.prototype.get=function(a){return this.m.has(a)?this.m.get(a):this.Ba?this.Ba.get(a):void 0};na.prototype.has=function(a){return!!this.m.has(a)||!(!this.Ba||!this.Ba.has(a))};var pa=function(a){var b=new na(a.aa,a);a.Zb&&b.Fa(a.Zb);b.oa(a.bc);b.Z=a.Z;return b};na.prototype.P=function(){return this.aa};
na.prototype.Fa=function(a){this.Zb=a};na.prototype.oa=function(a){this.bc=a};na.prototype.X=function(){this.m.X()};na.prototype.has=na.prototype.has;na.prototype.get=na.prototype.get;na.prototype.set=na.prototype.set;na.prototype.addImmutable=na.prototype.Lc;na.prototype.add=na.prototype.add;var qa=function(){},ra=function(a){return"function"==typeof a},sa=function(a){return"string"==typeof a},ta=function(a){return"number"==typeof a&&!isNaN(a)},ua=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},va=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},wa=function(a,b){if(a&&ua(a))for(var c=0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},xa=function(a,b){if(!ta(a)||
!ta(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Aa=function(a,b){for(var c=new ya,d=0;d<a.length;d++)c.set(a[d],!0);for(var e=0;e<b.length;e++)if(c.get(b[e]))return!0;return!1},Ba=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])},Ca=function(a){return!!a&&("[object Arguments]"==Object.prototype.toString.call(a)||Object.prototype.hasOwnProperty.call(a,"callee"))},Da=function(a){return Math.round(Number(a))||0},Ea=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},Fa=function(a){var b=[];if(ua(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Ga=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},Ha=function(){return(new Date).getTime()},ya=function(){this.prefix="gtm.";this.values={}};ya.prototype.set=function(a,b){this.values[this.prefix+a]=b};ya.prototype.get=function(a){return this.values[this.prefix+a]};ya.prototype.contains=function(a){return void 0!==this.get(a)};
var Ia=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Ja=function(a){var b=!1;return function(){if(!b)try{a()}catch(c){}b=!0}},La=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Ma=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1},Na=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c};var Oa=function(a,b){ka.call(this);this.ze=a;this.mg=b};fa(Oa,ka);var Qa=function(a,b){for(var c,d=0;d<b.length&&!(c=Pa(a,b[d]),c instanceof ha);d++);return c},Pa=function(a,b){try{var c=a.get(String(b[0]));if(!(c&&c instanceof Oa))throw Error("Attempting to execute non-function "+b[0]+".");return c.J.apply(c,[a].concat(b.slice(1)))}catch(e){var d=a.Zb;d&&d(e,b.context?{id:b[0],line:b.context.line}:null);throw e;}};Oa.prototype.toString=function(){return this.ze};Oa.prototype.getName=function(){return this.ze};
Oa.prototype.getName=Oa.prototype.getName;Oa.prototype.xa=function(){return new g(la(this))};Oa.prototype.getKeys=Oa.prototype.xa;Oa.prototype.J=function(a,b){var c=this;a.P().be();return this.mg.apply({evaluate:function(d){var e=a;return ua(d)?Pa(e,d):d},Rc:function(d){return Qa(a,d)},getName:function(){return c.getName()},P:function(){return a.P()},i:function(){return a}},Array.prototype.slice.call(arguments,1))};Oa.prototype.invoke=Oa.prototype.J;
Oa.prototype.Da=function(a,b){try{return this.J.apply(this,Array.prototype.slice.call(arguments,0))}catch(c){}};Oa.prototype.safeInvoke=Oa.prototype.Da;var Ra=function(){ka.call(this)};fa(Ra,ka);Ra.prototype.xa=function(){return new g(la(this))};Ra.prototype.getKeys=Ra.prototype.xa;var Sa=/^([a-z]*):(!|\?)(\*|string|boolean|number|Fn|Map|List)$/i,Ta={Fn:"function",Map:"Object",List:"Array"},Ua=function(a,b,c){for(var d=0;d<b.length;d++){var e=Sa.exec(b[d]);if(!e)throw Error("Internal Error in "+a);var f=e[1],h="!"===e[2],k=e[3],l=c[d],m=typeof l;if(null===l||"undefined"===m){if(h)throw Error("Error in "+a+". Required argument "+f+" not supplied.");}else if("*"!==k){var n=typeof l;l instanceof Oa?n="Fn":l instanceof g?n="List":l instanceof Ra&&(n="Map");if(n!=k)throw Error("Error in "+
a+". Argument "+f+" has type "+n+", which does not match required type "+(Ta[k]||k)+".");}}};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Va=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Wa=function(a){if(null==a)return String(a);var b=Va.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Xa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Ya=function(a){if(!a||"object"!=Wa(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Xa(a,"constructor")&&!Xa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Xa(a,b)},Za=function(a,b){var c=b||("array"==Wa(a)?[]:{}),d;for(d in a)if(Xa(a,d)){var e=a[d];"array"==Wa(e)?("array"!=Wa(c[d])&&(c[d]=[]),c[d]=Za(e,c[d])):Ya(e)?(Ya(c[d])||(c[d]={}),c[d]=Za(e,c[d])):c[d]=e}return c};var ab=function(a,b){var c=[],d=[],e=function(h,k){for(var l=la(h),m=0;m<l.length;m++)k[l[m]]=f(h.get(l[m]))},f=function(h){var k=va(c,h);if(-1<k)return d[k];if(h instanceof g){var l=[];c.push(h);d.push(l);for(var m=h.xa(),n=0;n<m.length();n++)l[m.get(n)]=f(h.get(m.get(n)));return l}if(h instanceof Ra){var q={};c.push(h);d.push(q);e(h,q);return q}if(h instanceof Oa){var t=function(){for(var p=Array.prototype.slice.call(arguments,0),r=0;r<p.length;r++)p[r]=$a(p[r],b);var v=b?b.P():ma(),w=new na(v);
b&&(w.Z=b.Z);return f(h.J.apply(h,[w].concat(p)))};c.push(h);d.push(t);e(h,t);return t}return h};return f(a)},$a=function(a,b){var c=[],d=[],e=function(h,k){for(var l in h)h.hasOwnProperty(l)&&k.set(l,f(h[l]))},f=function(h){var k=va(c,h);if(-1<k)return d[k];if(ua(h)||Ca(h)){var l=new g([]);c.push(h);d.push(l);for(var m in h)h.hasOwnProperty(m)&&l.set(m,f(h[m]));return l}if(Ya(h)){var n=new Ra;c.push(h);d.push(n);e(h,n);return n}if("function"===typeof h){var q=new Oa("",function(p){for(var r=Array.prototype.slice.call(arguments,
0),v=0;v<r.length;v++)r[v]=ab(this.evaluate(r[v]),b);return f((0,this.i().bc)(h,h,r))});c.push(h);d.push(q);e(h,q);return q}var t=typeof h;if(null===h||"string"===t||"number"===t||"boolean"===t)return h};return f(a)};var bb={control:function(a,b){return new ha(a,this.evaluate(b))},fn:function(a,b,c){var d=this.i(),e=this.evaluate(b);if(!(e instanceof g))throw Error("Error: non-List value given for Fn argument names.");var f=Array.prototype.slice.call(arguments,2);this.P().wa(a.length+f.length);return new Oa(a,function(){return function(h){var k=pa(d);void 0===k.Z&&(k.Z=this.i().Z);for(var l=Array.prototype.slice.call(arguments,0),m=0;m<l.length;m++)if(l[m]=this.evaluate(l[m]),l[m]instanceof ha)return l[m];for(var n=
e.get("length"),q=0;q<n;q++)q<l.length?k.set(e.get(q),l[q]):k.set(e.get(q),void 0);k.set("arguments",new g(l));var t=Qa(k,f);if(t instanceof ha)return"return"===t.K?t.getData():t}}())},list:function(a){var b=this.P();b.wa(arguments.length);for(var c=new g,d=0;d<arguments.length;d++){var e=this.evaluate(arguments[d]);"string"===typeof e&&b.wa(e.length?e.length-1:0);c.push(e)}return c},map:function(a){for(var b=this.P(),c=new Ra,d=0;d<arguments.length-1;d+=2){var e=this.evaluate(arguments[d])+"",f=
this.evaluate(arguments[d+1]),h=e.length;h+="string"===typeof f?f.length:1;b.wa(h);c.set(e,f)}return c},undefined:function(){}};function cb(a,b){var c=Pa(a,b);if(c instanceof ha||c instanceof Oa||c instanceof g||c instanceof Ra||null===c||void 0===c||"string"===typeof c||"number"===typeof c||"boolean"===typeof c)return c}var fb=function(){this.aa=ma();this.ya=new na(this.aa)};aa=fb.prototype;aa.va=function(a,b){var c=new Oa(a,b);c.X();this.ya.set(a,c)};aa.Zd=function(a,b){bb.hasOwnProperty(a)&&this.va(b||a,bb[a])};aa.P=function(){return this.aa};aa.gc=function(){this.aa=ma();this.ya.aa=this.aa};aa.Fa=function(a){this.ya.Fa(a)};
aa.oa=function(a){this.ya.oa(a)};aa.Qa=function(a,b){var c=Array.prototype.slice.call(arguments,0);return this.pd(c)};aa.pd=function(a){for(var b,c=0;c<arguments.length;c++)b=cb(this.ya,arguments[c]);return b};aa.hc=function(a,b){var c=pa(this.ya);c.Z=a;for(var d,e=1;e<arguments.length;e++)d=cb(c,arguments[e]);return d};aa.X=function(){this.ya.X()};fb.prototype.makeImmutable=fb.prototype.X;fb.prototype.run=fb.prototype.pd;fb.prototype.execute=fb.prototype.Qa;fb.prototype.setJavaScriptProxy=fb.prototype.oa;
fb.prototype.resetQuota=fb.prototype.gc;fb.prototype.getQuota=fb.prototype.P;fb.prototype.addNativeInstruction=fb.prototype.Zd;fb.prototype.addInstruction=fb.prototype.va;var gb=function(a){for(var b=[],c=0;c<a.length();c++)a.has(c)&&(b[c]=a.get(c));return b};var hb={uh:"concat every filter forEach hasOwnProperty indexOf join lastIndexOf map pop push reduce reduceRight reverse shift slice some sort splice unshift toString".split(" "),concat:function(a,b){for(var c=[],d=0;d<this.length();d++)c.push(this.get(d));for(var e=1;e<arguments.length;e++)if(arguments[e]instanceof g)for(var f=arguments[e],h=0;h<f.length();h++)c.push(f.get(h));else c.push(arguments[e]);return new g(c)},every:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)if(this.has(d)&&
!b.J(a,this.get(d),d,this))return!1;return!0},filter:function(a,b){for(var c=this.length(),d=[],e=0;e<this.length()&&e<c;e++)this.has(e)&&b.J(a,this.get(e),e,this)&&d.push(this.get(e));return new g(d)},forEach:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)this.has(d)&&b.J(a,this.get(d),d,this)},hasOwnProperty:function(a,b){return this.has(b)},indexOf:function(a,b,c){var d=this.length(),e=void 0===c?0:Number(c);0>e&&(e=Math.max(d+e,0));for(var f=e;f<d;f++)if(this.has(f)&&this.get(f)===
b)return f;return-1},join:function(a,b){for(var c=[],d=0;d<this.length();d++)c.push(this.get(d));return c.join(b)},lastIndexOf:function(a,b,c){var d=this.length(),e=d-1;void 0!==c&&(e=0>c?d+c:Math.min(c,e));for(var f=e;0<=f;f--)if(this.has(f)&&this.get(f)===b)return f;return-1},map:function(a,b){for(var c=this.length(),d=[],e=0;e<this.length()&&e<c;e++)this.has(e)&&(d[e]=b.J(a,this.get(e),e,this));return new g(d)},pop:function(){return this.pop()},push:function(a,b){return this.push.apply(this,Array.prototype.slice.call(arguments,
1))},reduce:function(a,b,c){var d=this.length(),e,f;if(void 0!==c)e=c,f=0;else{if(0==d)throw Error("TypeError: Reduce on List with no elements.");var h;for(h=0;h<d;h++)if(this.has(h)){e=this.get(h);f=h+1;break}if(h==d)throw Error("TypeError: Reduce on List with no elements.");}for(var k=f;k<d;k++)this.has(k)&&(e=b.J(a,e,this.get(k),k,this));return e},reduceRight:function(a,b,c){var d=this.length(),e,f;if(void 0!==c)e=c,f=d-1;else{if(0==d)throw Error("TypeError: ReduceRight on List with no elements.");
var h;for(h=1;h<=d;h++)if(this.has(d-h)){e=this.get(d-h);f=d-(h+1);break}if(h>d)throw Error("TypeError: ReduceRight on List with no elements.");}for(var k=f;0<=k;k--)this.has(k)&&(e=b.J(a,e,this.get(k),k,this));return e},reverse:function(){for(var a=gb(this),b=a.length-1,c=0;0<=b;b--,c++)a.hasOwnProperty(b)?this.set(c,a[b]):this.remove(c);return this},shift:function(){return this.shift()},slice:function(a,b,c){var d=this.length();void 0===b&&(b=0);b=0>b?Math.max(d+b,0):Math.min(b,d);c=void 0===c?
d:0>c?Math.max(d+c,0):Math.min(c,d);c=Math.max(b,c);for(var e=[],f=b;f<c;f++)e.push(this.get(f));return new g(e)},some:function(a,b){for(var c=this.length(),d=0;d<this.length()&&d<c;d++)if(this.has(d)&&b.J(a,this.get(d),d,this))return!0;return!1},sort:function(a,b){var c=gb(this);void 0===b?c.sort():c.sort(function(e,f){return Number(b.J(a,e,f))});for(var d=0;d<c.length;d++)c.hasOwnProperty(d)?this.set(d,c[d]):this.remove(d)},splice:function(a,b,c,d){return this.splice.apply(this,Array.prototype.splice.call(arguments,
1,arguments.length-1))},toString:function(){return this.toString()},unshift:function(a,b){return this.unshift.apply(this,Array.prototype.slice.call(arguments,1))}};var ib={ADD:0,AND:1,APPLY:2,ASSIGN:3,BLOCK:53,BREAK:4,CASE:5,CONST:52,CONTINUE:6,CONTROL:49,CREATE_ARRAY:7,CREATE_OBJECT:8,DEFAULT:9,DEFN:50,DIVIDE:10,DO:11,EQUALS:12,EXPRESSION_LIST:13,FN:51,FOR:14,FOR_IN:47,FOR_IN_CONST:54,FOR_IN_LET:55,GET:15,GET_CONTAINER_VARIABLE:48,GET_INDEX:16,GET_PROPERTY:17,GREATER_THAN:18,GREATER_THAN_EQUALS:19,IDENTITY_EQUALS:20,IDENTITY_NOT_EQUALS:21,IF:22,LESS_THAN:23,LESS_THAN_EQUALS:24,MODULUS:25,MULTIPLY:26,NEGATE:27,NOT:28,NOT_EQUALS:29,NULL:45,OR:30,PLUS_EQUALS:31,
POST_DECREMENT:32,POST_INCREMENT:33,PRE_DECREMENT:34,PRE_INCREMENT:35,QUOTE:46,RETURN:36,SET_PROPERTY:43,SUBTRACT:37,SWITCH:38,TERNARY:39,TYPEOF:40,UNDEFINED:44,VAR:41,WHILE:42},jb="charAt concat indexOf lastIndexOf match replace search slice split substring toLowerCase toLocaleLowerCase toString toUpperCase toLocaleUpperCase trim".split(" "),kb=new ha("break"),lb=new ha("continue"),mb=function(a,b){return this.evaluate(a)+this.evaluate(b)},nb=function(a,b){return this.evaluate(a)&&this.evaluate(b)},
ob=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!(c instanceof g))throw Error("Error: Non-List argument given to Apply instruction.");if(null===a||void 0===a)throw Error("TypeError: Can't read property "+b+" of "+a+".");if("boolean"==typeof a||"number"==typeof a){if("toString"==b)return a.toString();throw Error("TypeError: "+a+"."+b+" is not a function.");}if("string"==typeof a){if(0<=va(jb,b))return $a(a[b].apply(a,gb(c)),this.i());throw Error("TypeError: "+b+" is not a function");
}if(a instanceof g){if(a.has(b)){var d=a.get(b);if(d instanceof Oa){var e=gb(c);e.unshift(this.i());return d.J.apply(d,e)}throw Error("TypeError: "+b+" is not a function");}if(0<=va(hb.uh,b)){var f=gb(c);f.unshift(this.i());return hb[b].apply(a,f)}}if(a instanceof Oa||a instanceof Ra){if(a.has(b)){var h=a.get(b);if(h instanceof Oa){var k=gb(c);k.unshift(this.i());return h.J.apply(h,k)}throw Error("TypeError: "+b+" is not a function");}if("toString"==b)return a instanceof Oa?a.getName():a.toString();
if("hasOwnProperty"==b)return a.has.apply(a,gb(c))}throw Error("TypeError: Object has no '"+b+"' property.");},qb=function(a,b){a=this.evaluate(a);if("string"!=typeof a)throw Error("Invalid key name given for assignment.");var c=this.i();if(!c.has(a))throw Error("Attempting to assign to undefined value "+b);var d=this.evaluate(b);c.set(a,d);return d},rb=function(a){var b=pa(this.i()),c=Qa(b,Array.prototype.slice.apply(arguments));if(c instanceof ha)return c},sb=function(){return kb},tb=function(a){for(var b=
this.evaluate(a),c=0;c<b.length;c++){var d=this.evaluate(b[c]);if(d instanceof ha)return d}},ub=function(a){for(var b=this.i(),c=0;c<arguments.length-1;c+=2){var d=arguments[c];if("string"==typeof d){var e=this.evaluate(arguments[c+1]);b.Lc(d,e)}}},vb=function(){return lb},wb=function(a,b,c){var d=new g;b=this.evaluate(b);for(var e=0;e<b.length;e++)d.push(b[e]);var f=[ib.FN,a,d].concat(Array.prototype.splice.call(arguments,2,arguments.length-2));this.i().set(a,this.evaluate(f))},xb=function(a,b){return this.evaluate(a)/
this.evaluate(b)},yb=function(a,b){return this.evaluate(a)==this.evaluate(b)},zb=function(a){for(var b,c=0;c<arguments.length;c++)b=this.evaluate(arguments[c]);return b};
function Ab(a,b,c){if("string"==typeof b)for(var d=0;d<b.length;d++){var e=a(d),f=Qa(e,c);if(f instanceof ha){if("break"==f.K)break;if("return"==f.K)return f}}else if(b instanceof Ra||b instanceof g||b instanceof Oa)for(var h=b.xa(),k=h.length(),l=0;l<k;l++){var m=a(h.get(l)),n=Qa(m,c);if(n instanceof ha){if("break"==n.K)break;if("return"==n.K)return n}}}
var Bb=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);var d=this.i();return Ab(function(e){d.set(a,e);return d},b,c)},Db=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);var d=this.i();return Ab(function(e){var f=pa(d);f.Lc(a,e);return f},b,c)},Eb=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);var d=this.i();return Ab(function(e){var f=pa(d);f.add(a,e);return f},b,c)},Fb=function(a){return this.i().get(this.evaluate(a))},
Gb=function(a,b){var c;a=this.evaluate(a);b=this.evaluate(b);if(void 0===a||null===a)throw Error("TypeError: cannot access property of "+a+".");a instanceof Ra||a instanceof g||a instanceof Oa?c=a.get(b):"string"==typeof a&&("length"==b?c=a.length:ia(b)&&(c=a[b]));return c},Hb=function(a,b){return this.evaluate(a)>this.evaluate(b)},Ib=function(a,b){return this.evaluate(a)>=this.evaluate(b)},Jb=function(a,b){return this.evaluate(a)===this.evaluate(b)},Kb=function(a,b){return this.evaluate(a)!==this.evaluate(b)},
Lb=function(a,b,c){var d=[];this.evaluate(a)?d=this.evaluate(b):c&&(d=this.evaluate(c));var e=this.Rc(d);if(e instanceof ha)return e},Mb=function(a,b){return this.evaluate(a)<this.evaluate(b)},Nb=function(a,b){return this.evaluate(a)<=this.evaluate(b)},Ob=function(a,b){return this.evaluate(a)%this.evaluate(b)},Pb=function(a,b){return this.evaluate(a)*this.evaluate(b)},Qb=function(a){return-this.evaluate(a)},Rb=function(a){return!this.evaluate(a)},Sb=function(a,b){return this.evaluate(a)!=this.evaluate(b)},
Tb=function(){return null},Ub=function(a,b){return this.evaluate(a)||this.evaluate(b)},Vb=function(a,b){var c=this.evaluate(a);this.evaluate(b);return c},Wb=function(a){return this.evaluate(a)},Xb=function(a){return Array.prototype.slice.apply(arguments)},Yb=function(a){return new ha("return",this.evaluate(a))},Zb=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(null===a||void 0===a)throw Error("TypeError: Can't set property "+b+" of "+a+".");(a instanceof Oa||a instanceof
g||a instanceof Ra)&&a.set(b,c);return c},$b=function(a,b){return this.evaluate(a)-this.evaluate(b)},ac=function(a,b,c){a=this.evaluate(a);b=this.evaluate(b);c=this.evaluate(c);if(!ua(b)||!ua(c))throw Error("Error: Malformed switch instruction.");for(var d,e=!1,f=0;f<b.length;f++)if(e||a===this.evaluate(b[f]))if(d=this.evaluate(c[f]),d instanceof ha){var h=d.K;if("break"==h)return;if("return"==h||"continue"==h)return d}else e=!0;if(c.length==b.length+1&&(d=this.evaluate(c[c.length-1]),d instanceof
ha&&("return"==d.K||"continue"==d.K)))return d},bc=function(a,b,c){return this.evaluate(a)?this.evaluate(b):this.evaluate(c)},cc=function(a){a=this.evaluate(a);return a instanceof Oa?"function":typeof a},dc=function(a){for(var b=this.i(),c=0;c<arguments.length;c++){var d=arguments[c];"string"!=typeof d||b.add(d,void 0)}},ec=function(a,b,c,d){var e,f=this.evaluate(d);if(this.evaluate(c)&&(e=this.Rc(f),e instanceof ha)){if("break"==e.K)return;if("return"==e.K)return e}for(;this.evaluate(a);){e=this.Rc(f);
if(e instanceof ha){if("break"==e.K)break;if("return"==e.K)return e}this.evaluate(b)}};var gc=function(){this.se=!1;this.W=new fb;fc(this);this.se=!0};gc.prototype.Hg=function(){return this.se};gc.prototype.isInitialized=gc.prototype.Hg;gc.prototype.Qa=function(a){return this.W.pd(a)};gc.prototype.execute=gc.prototype.Qa;gc.prototype.hc=function(a,b){return this.W.hc(a,b)};gc.prototype.runProgram=gc.prototype.hc;gc.prototype.X=function(){this.W.X()};gc.prototype.makeImmutable=gc.prototype.X;
var fc=function(a){function b(f,h){e.W.Zd(f,String(h))}function c(f,h){e.W.va(String(d[f]),h)}var d=ib,e=a;b("control",d.CONTROL);b("fn",d.FN);b("list",d.CREATE_ARRAY);b("map",d.CREATE_OBJECT);b("undefined",d.UNDEFINED);c("ADD",mb);c("AND",nb);c("APPLY",ob);c("ASSIGN",qb);c("BLOCK",rb);c("BREAK",sb);c("CASE",tb);c("CONST",ub);c("CONTINUE",vb);c("DEFAULT",tb);c("DEFN",wb);c("DIVIDE",xb);c("EQUALS",yb);c("EXPRESSION_LIST",zb);c("FOR_IN",Bb);c("FOR_IN_CONST",Db);c("FOR_IN_LET",Eb);c("GET",Fb);c("GET_INDEX",
Gb);c("GET_PROPERTY",Gb);c("GREATER_THAN",Hb);c("GREATER_THAN_EQUALS",Ib);c("IDENTITY_EQUALS",Jb);c("IDENTITY_NOT_EQUALS",Kb);c("IF",Lb);c("LESS_THAN",Mb);c("LESS_THAN_EQUALS",Nb);c("MODULUS",Ob);c("MULTIPLY",Pb);c("NEGATE",Qb);c("NOT",Rb);c("NOT_EQUALS",Sb);c("NULL",Tb);c("OR",Ub);c("POST_DECREMENT",Vb);c("POST_INCREMENT",Vb);c("PRE_DECREMENT",Wb);c("PRE_INCREMENT",Wb);c("QUOTE",Xb);c("RETURN",Yb);c("SET_PROPERTY",Zb);c("SUBTRACT",$b);c("SWITCH",ac);c("TERNARY",bc);c("TYPEOF",cc);c("VAR",dc);c("WHILE",
ec)};gc.prototype.va=function(a,b){this.W.va(a,b)};gc.prototype.addInstruction=gc.prototype.va;gc.prototype.P=function(){return this.W.P()};gc.prototype.getQuota=gc.prototype.P;gc.prototype.gc=function(){this.W.gc()};gc.prototype.resetQuota=gc.prototype.gc;gc.prototype.Fa=function(a){this.W.Fa(a)};gc.prototype.oa=function(a){this.W.oa(a)};gc.prototype.setJavaScriptProxy=gc.prototype.oa;var hc=function(){this.ac={}};hc.prototype.get=function(a){return this.ac.hasOwnProperty(a)?this.ac[a]:void 0};hc.prototype.add=function(a,b){if(this.ac.hasOwnProperty(a))throw"Attempting to add a function which already exists: "+a+".";if(!b)throw"Attempting to add an undefined function: "+a+".";var c=new Oa(a,function(){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<d.length;e++)d[e]=this.evaluate(d[e]);return b.apply(this,d)});c.X();this.ac[a]=c};
hc.prototype.addAll=function(a){for(var b in a)a.hasOwnProperty(b)&&this.add(b,a[b])};var u=window,A=document,ic=navigator,jc=A.currentScript&&A.currentScript.src,lc=function(a,b){var c=u[a];u[a]=void 0===c?b:c;return u[a]},mc=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},nc=function(a,b,c){var d=A.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;mc(d,b);c&&(d.onerror=c);var e;if(null===ea)b:{var f=ca.document,h=f.querySelector&&f.querySelector("script[nonce]");
if(h){var k=h.nonce||h.getAttribute("nonce");if(k&&da.test(k)){ea=k;break b}}ea=""}e=ea;e&&d.setAttribute("nonce",e);var l=A.getElementsByTagName("script")[0]||A.body||A.head;l.parentNode.insertBefore(d,l);return d},oc=function(){if(jc){var a=jc.toLowerCase();if(0===a.indexOf("https://"))return 2;if(0===a.indexOf("http://"))return 3}return 1},pc=function(a,b){var c=A.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=A.body&&A.body.lastChild||
A.body||A.head;d.parentNode.insertBefore(c,d);mc(c,b);void 0!==a&&(c.src=a);return c},qc=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a;return d},rc=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},sc=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},D=function(a){u.setTimeout(a,0)},tc=function(a,b){return a&&
b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},uc=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},vc=function(a){var b=A.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},wc=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;for(var f=a,h=0;f&&h<=c;h++){if(d[String(f.tagName).toLowerCase()])return f;
f=f.parentElement}return null},xc=function(a,b){var c=a[b];c&&"string"===typeof c.animVal&&(c=c.animVal);return c};var yc=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var zc={},Ac=function(a,b){zc[a]=zc[a]||[];zc[a][b]=!0},Bc=function(a){for(var b=[],c=zc[a]||[],d=0;d<c.length;d++)c[d]&&(b[Math.floor(d/6)]^=1<<d%6);for(var e=0;e<b.length;e++)b[e]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b[e]||0);return b.join("")};var Cc=/:[0-9]+$/,Dc=function(a,b,c,d){for(var e=[],f=a.split("&"),h=0;h<f.length;h++){var k=f[h].split("=");if(decodeURIComponent(k[0]).replace(/\+/g," ")===b){var l=k.slice(1).join("=");if(!c)return d?l:decodeURIComponent(l).replace(/\+/g," ");e.push(d?l:decodeURIComponent(l).replace(/\+/g," "))}}return c?e:void 0},Gc=function(a,b,c,d,e){b&&(b=String(b).toLowerCase());if("protocol"===b||"port"===b)a.protocol=Ec(a.protocol)||Ec(u.location.protocol);"port"===b?a.port=String(Number(a.hostname?a.port:
u.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===b&&(a.hostname=(a.hostname||u.location.hostname).replace(Cc,"").toLowerCase());return Fc(a,b,c,d,e)},Fc=function(a,b,c,d,e){var f,h=Ec(a.protocol);b&&(b=String(b).toLowerCase());switch(b){case "url_no_fragment":f=Hc(a);break;case "protocol":f=h;break;case "host":f=a.hostname.replace(Cc,"").toLowerCase();if(c){var k=/^www\d*\./.exec(f);k&&k[0]&&(f=f.substr(k[0].length))}break;case "port":f=String(Number(a.port)||("http"==
h?80:"https"==h?443:""));break;case "path":a.pathname||a.hostname||Ac("TAGGING",1);f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var l=f.split("/");0<=va(d||[],l[l.length-1])&&(l[l.length-1]="");f=l.join("/");break;case "query":f=a.search.replace("?","");e&&(f=Dc(f,e,!1,void 0));break;case "extension":var m=a.pathname.split(".");f=1<m.length?m[m.length-1]:"";f=f.split("/")[0];break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Ec=function(a){return a?a.replace(":",
"").toLowerCase():""},Hc=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,c)}return b},Ic=function(a){var b=A.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||Ac("TAGGING",1),c="/"+c);var d=b.hostname.replace(Cc,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}};var Jc=function(a,b,c){for(var d=[],e=String(b||document.cookie).split(";"),f=0;f<e.length;f++){var h=e[f].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d},Mc=function(a,b,c,d){var e=Kc(a,d);if(1===e.length)return e[0].id;if(0!==e.length){e=Lc(e,function(f){return f.Wb},b);if(1===e.length)return e[0].id;e=Lc(e,function(f){return f.ob},c);return e[0]?e[0].id:void 0}};
function Nc(a,b,c){var d=document.cookie;document.cookie=a;var e=document.cookie;return d!=e||void 0!=c&&0<=Jc(b,e).indexOf(c)}
var Qc=function(a,b,c,d,e){var f;if(void 0==b)f=a+"=deleted; expires="+(new Date(0)).toUTCString();else{d&&(b=encodeURIComponent(b));var h=b;h&&1200<h.length&&(h=h.substring(0,1200));b=h;f=a+"="+b}var k=void 0,l=void 0,m;for(m in c)if(c.hasOwnProperty(m)){var n=c[m];if(null!=n)switch(m){case "secure":n&&(f+="; secure");break;case "domain":k=n;break;default:"path"==m&&(l=n),"expires"==m&&n instanceof Date&&(n=n.toUTCString()),f+="; "+m+"="+n}}if("auto"===k){for(var q=Oc(),t=void 0,p=0,r=0;r<q.length;++r){var v=
"none"!=q[r]?q[r]:void 0;if(e){c.domain=v;try{e(a,c)}catch(w){t=w;continue}}p+=1;if(!Pc(v,l)&&Nc(f+(v?"; domain="+v:""),a,b))return!0}if(t&&!p)throw t;return!1}e&&e(a,c);k&&"none"!=k&&(f+="; domain="+k);return!Pc(k,l)&&Nc(f,a,b)},Rc=function(a,b,c,d,e,f){d=d||"auto";var h={path:c||"/"};e&&(h.expires=e);"none"!==d&&(h.domain=d);return Qc(a,b,h,f)};
function Lc(a,b,c){for(var d=[],e=[],f,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===f||l<f?(e=[k],f=l):l===f&&e.push(k)}return 0<d.length?d:e}function Kc(a,b){for(var c=[],d=Jc(a),e=0;e<d.length;e++){var f=d[e].split("."),h=f.shift();if(!b||-1!==b.indexOf(h)){var k=f.shift();k&&(k=k.split("-"),c.push({id:f.join("."),Wb:1*k[0]||1,ob:1*k[1]||1}))}}return c}
var Tc=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Uc=/(^|\.)doubleclick\.net$/i,Pc=function(a,b){return Uc.test(document.location.hostname)||"/"===b&&Tc.test(a)},Oc=function(){var a=[],b=document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(var d=b.length-2;0<=d;d--)a.push(b.slice(d).join("."));a.push("none");return a};var Vc=function(a,b,c){var d=a.i().Z;if(!d)throw Error("invalid program state");d.Jf.apply(null,Array.prototype.slice.call(arguments,1))},Wc=function(a,b){Ua(this.getName(),["path:!string"],[a]);Vc(this,"access_globals","execute",a);for(var c=a.split("."),d=u,e=d[c[0]],f=1;e&&f<c.length;f++)d=e,e=e[c[f]];if("function"===Wa(e)){for(var h=[],k=1;k<arguments.length;k++)h.push(ab(arguments[k],this.i()));return $a((0,this.i().bc)(e,d,h),this.i())}},Xc=function(a){Ua(this.getName(),["fn:!Fn"],arguments);
var b=this.i();D(function(){a instanceof Oa&&a.Da(b)})},Yc=function(a){Ua(this.getName(),["path:!string"],arguments);Vc(this,"access_globals","read",a);var b=a.split("."),c=u,d;for(d=0;d<b.length-1;d++)if(c=c[b[d]],null==c)return;return $a(c[b[d]],this.i())},Zc=function(a,b){b=void 0===b?!0:b;Ua(this.getName(),["name:!string","decode:?boolean"],arguments);Vc(this,"get_cookies",a);return $a(Jc(a,void 0,!!b),this.i())},$c=function(a){Ua(this.getName(),["component:?string"],arguments);Vc(this,"get_referrer",
a);return Fc(Ic(u.document.referrer),a)},ad=function(a){Ua(this.getName(),["component:?string"],arguments);Vc(this,"get_url",a);return Gc(Ic(u.location.href),a)},cd=function(a,b){Ua(this.getName(),["queryKey:!string","retrieveAll:?boolean"],arguments);Vc(this,"get_url","query",a);return bd(this.i(),u.location.href,a,b)},dd=function(a,b){Ua(this.getName(),["queryKey:!string","retrieveAll:?boolean"],arguments);Vc(this,"get_referrer","query",a);return bd(this.i(),u.document.referrer,a,b)};
function bd(a,b,c,d){var e=Gc(Ic(b),"query"),f=Dc(e,c,d);return $a(f,a)}
var ed=function(a,b){Ua(this.getName(),["url:!string","onSuccess:?Fn"],arguments);Vc(this,"inject_hidden_iframe",a);var c=this.i();pc(a,function(){b instanceof Oa&&b.Da(c)})},fd={},gd=function(a,b,c,d){Ua(this.getName(),["url:!string","onSuccess:?Fn","onFailure:?Fn","cacheToken:?string"],arguments);Vc(this,"inject_script",a);var e=this.i(),f=function(){b instanceof Oa&&b.Da(e)},h=function(){c instanceof Oa&&c.Da(e)};if(d){var k=d;fd[k]?(fd[k].onSuccess.push(f),fd[k].onFailure.push(h)):(fd[k]={onSuccess:[f],
onFailure:[h]},f=function(){for(var l=fd[k].onSuccess,m=0;m<l.length;m++)D(l[m]);l.push=function(n){D(n);return 0}},h=function(){for(var l=fd[k].onFailure,m=0;m<l.length;m++)D(l[m]);fd[k]=null},nc(a,f,h))}else nc(a,f,h)},hd=function(){try{Vc(this,"logging")}catch(c){return}if(console){for(var a=Array.prototype.slice.call(arguments,0),b=0;b<a.length;b++)a[b]=ab(a[b],this.i());console.log.apply(console,a)}},id=function(a,b,c){Ua(this.getName(),["url:!string","onSuccess:?Fn","onFailure:?Fn"],arguments);
Vc(this,"send_pixel",a);var d=this.i();qc(a,function(){b instanceof Oa&&b.Da(d)},function(){c instanceof Oa&&c.Da(d)})},jd=function(a,b,c,d){var e=this;d=void 0===d?!0:d;Ua(this.getName(),["name:!string","value:?string","options:?Map","encode:?boolean"],arguments);var f=c?ab(c,this.i()):void 0;return Qc(a,b,f,!!d,function(h,k){return Vc(e,"set_cookies",h,k)})},kd=function(a,b,c){Ua(this.getName(),["path:!string","value:?*","overrideExisting:?boolean"],arguments);Vc(this,"access_globals","readwrite",
a);var d=a.split("."),e=u,f;for(f=0;f<d.length-1;f++)if(e=e[d[f]],void 0===e)return!1;return void 0===e[d[f]]||c?(e[d[f]]=ab(b,this.i()),!0):!1},md=function(a){Ua(this.getName(),["path:!string"],arguments);Vc(this,"access_globals","readwrite",a);var b=a.split("."),c=ld(b),d=b[b.length-1];if(void 0===c)throw Error("Path "+a+" does not exist.");var e=c[d];void 0===e&&(e=[],c[d]=e);return $a(function(){if(!ra(e.push))throw Error("Object at "+a+" in window is not an array.");e.push.apply(e,Array.prototype.slice.call(arguments,
0))},this.i())},nd=function(a,b){Ua(this.getName(),["functionPath:!string","arrayPath:!string"],arguments);Vc(this,"access_globals","readwrite",a);Vc(this,"access_globals","readwrite",b);var c=a.split("."),d=ld(c),e=c[c.length-1];if(void 0===d)throw Error("Path "+a+" does not exist.");var f=d[e];if(f&&!ra(f))return null;if(f)return $a(f,this.i());var h;f=function(){if(!ra(h.push))throw Error("Object at "+b+" in window is not an array.");h.push.call(h,arguments)};d[e]=f;var k=b.split("."),l=ld(k),
m=k[k.length-1];if(void 0===l)throw Error("Path "+k+" does not exist.");h=l[m];void 0===h&&(h=[],l[m]=h);return $a(function(){f.apply(f,Array.prototype.slice.call(arguments,0))},this.i())},od=function(a,b){Ua(this.getName(),["toPath:!string","fromPath:!string"],arguments);Vc(this,"access_globals","write",a);Vc(this,"access_globals","read",b);var c=a.split("."),d=b.split("."),e=ld(c),f=ld(d);if(void 0===e||void 0===f)return!1;e[c[c.length-1]]=f[d[d.length-1]];return!0};
function ld(a){for(var b=u,c=0;c<a.length-1;c++){if(!b.hasOwnProperty(a[c]))return;b=b[a[c]]}return b}var pd=function(a,b){Ua(this.getName(),["permission:!string"],[a]);for(var c=Array.prototype.slice.call(arguments,0),d=0;d<c.length;++d)c[d]=ab(c[d],this.i());c.unshift(this);try{return Vc.apply(null,c),!0}catch(e){return!1}},qd=function(a){Ua(this.getName(),["uri:!string"],arguments);return encodeURI(a)},rd=function(a){Ua(this.getName(),["uri:!string"],arguments);return encodeURIComponent(a)};var Nd,Od=[],Pd=[],Qd=[],Rd=[],Sd=[],Td={},Ud,Vd,Wd,Xd=function(a,b){var c={};c["function"]="__"+a;for(var d in b)b.hasOwnProperty(d)&&(c["vtp_"+d]=b[d]);return c},Yd=function(a,b){var c=a["function"];if(!c)throw Error("Error: No function name given for function call.");var d=!!Td[c],e={},f;for(f in a)a.hasOwnProperty(f)&&0===f.indexOf("vtp_")&&(e[d?f:f.substr(4)]=a[f]);return d?Td[c](e):Nd(c,e,b)},$d=function(a,b,c){c=c||[];var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=Zd(a[e],b,c));return d},
ae=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=Td[b];return c?c.priorityOverride||0:0},Zd=function(a,b,c){if(ua(a)){var d;switch(a[0]){case "function_id":return a[1];case "list":d=[];for(var e=1;e<a.length;e++)d.push(Zd(a[e],b,c));return d;case "macro":var f=a[1];if(c[f])return;var h=Od[f];if(!h||b.Yc(h))return;c[f]=!0;try{var k=$d(h,b,c);k.vtp_gtmEventId=b.id;d=Yd(k,b);Wd&&(d=Wd.Zf(d,k))}catch(w){b.xe&&b.xe(w,Number(f)),d=!1}c[f]=!1;return d;
case "map":d={};for(var l=1;l<a.length;l+=2)d[Zd(a[l],b,c)]=Zd(a[l+1],b,c);return d;case "template":d=[];for(var m=!1,n=1;n<a.length;n++){var q=Zd(a[n],b,c);Vd&&(m=m||q===Vd.Kb);d.push(q)}return Vd&&m?Vd.bg(d):d.join("");case "escape":d=Zd(a[1],b,c);if(Vd&&ua(a[1])&&"macro"===a[1][0]&&Vd.Ig(a))return Vd.Yg(d);d=String(d);for(var t=2;t<a.length;t++)sd[a[t]]&&(d=sd[a[t]](d));return d;case "tag":var p=a[1];if(!Rd[p])throw Error("Unable to resolve tag reference "+p+".");return d={fe:a[2],index:p};case "zb":var r=
{arg0:a[2],arg1:a[3],ignore_case:a[5]};r["function"]=a[1];var v=be(r,b,c);a[4]&&(v=!v);return v;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},be=function(a,b,c){try{return Ud($d(a,b,c))}catch(d){JSON.stringify(a)}return null};var ce=function(){var a=function(b){return{toString:function(){return b}}};return{Bd:a("convert_case_to"),Cd:a("convert_false_to"),Dd:a("convert_null_to"),Ed:a("convert_true_to"),Fd:a("convert_undefined_to"),sa:a("function"),pf:a("instance_name"),qf:a("live_only"),rf:a("malware_disabled"),sf:a("metadata"),Jh:a("original_vendor_template_id"),tf:a("once_per_event"),Td:a("once_per_load"),Ud:a("setup_tags"),Vd:a("tag_id"),Wd:a("teardown_tags")}}();var de=function(a,b,c){this.Wg=a;this.Tg=b;this.Ng=c};fa(de,Error);de.prototype.getParameters=function(){return this.Tg};var ee=function(a,b){if(ua(a)){Object.defineProperty(a,"context",{value:{line:b[0]}});for(var c=1;c<a.length;c++)ee(a[c],b[c])}};var ge=function(){return function(a,b){a instanceof fe||(a=new fe(a));b&&a.de.push(b);throw a;}},fe=function(a){this.Rg=a;this.de=[]};fa(fe,Error);var he=null,ke=function(a){function b(q){for(var t=0;t<q.length;t++)d[q[t]]=!0}var c=[],d=[];he=ie(a);for(var e=0;e<Pd.length;e++){var f=Pd[e],h=je(f);if(h){for(var k=f.add||[],l=0;l<k.length;l++)c[k[l]]=!0;b(f.block||[])}else null===h&&b(f.block||[])}for(var m=[],n=0;n<Rd.length;n++)c[n]&&!d[n]&&(m[n]=!0);return m},je=function(a){for(var b=a["if"]||[],c=0;c<b.length;c++){var d=he(b[c]);if(!d)return null===d?null:!1}for(var e=a.unless||[],f=0;f<e.length;f++){var h=he(e[f]);if(null===h)return null;
if(h)return!1}return!0},ie=function(a){var b=[];return function(c){void 0===b[c]&&(b[c]=be(Qd[c],a));return b[c]}};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var ze={},Ae=null,Be=Math.random();ze.o="GTM-TKT4VZ7";ze.Ob="6k2";var Ce={__cl:!0,__ecl:!0,__ehl:!0,__evl:!0,__fal:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0},De="www.googletagmanager.com/gtm.js";var Ee=De,Fe=null,Ge=null,He=null,Ie="//www.googletagmanager.com/a?id="+ze.o+"&cv=17",Je={},Ke={},Le=function(){var a=Ae.sequence||0;Ae.sequence=a+1;return a};var G=function(a,b,c,d){return(2===Me()||d||"http:"!=u.location.protocol?a:b)+c},Me=function(){var a=oc(),b;if(1===a)a:{var c=Ee;c=c.toLowerCase();for(var d="https://"+c,e="http://"+c,f=1,h=A.getElementsByTagName("script"),k=0;k<h.length&&100>k;k++){var l=h[k].src;if(l){l=l.toLowerCase();if(0===l.indexOf(e)){b=3;break a}1===f&&0===l.indexOf(d)&&(f=2)}}b=f}else b=a;return b};var Ne=!1;
var Re=function(){return"&tc="+Rd.filter(function(a){return a}).length},$e=function(){Se&&(u.clearTimeout(Se),Se=void 0);void 0===Te||Ue[Te]&&!Ve||(We[Te]||Xe.Kg()||0>=Ye--?(Ac("GTM",1),We[Te]=!0):(Xe.jh(),qc(Ze()),Ue[Te]=!0,Ve=""))},Ze=function(){var a=Te;if(void 0===a)return"";var b=Bc("GTM"),c=Bc("TAGGING");return[af,Ue[a]?"":"&es=1",bf[a],b?"&u="+b:"",c?"&ut="+c:"",Re(),Ve,"&z=0"].join("")},cf=function(){return[Ie,"&v=3&t=t","&pid="+xa(),"&rv="+ze.Ob].join("")},df="0.005000">
Math.random(),af=cf(),ef=function(){af=cf()},Ue={},Ve="",Te=void 0,bf={},We={},Se=void 0,Xe=function(a,b){var c=0,d=0;return{Kg:function(){if(c<a)return!1;Ha()-d>=b&&(c=0);return c>=a},jh:function(){Ha()-d>=b&&(c=0);c++;d=Ha()}}}(2,1E3),Ye=1E3,ff=function(a,b){if(df&&!We[a]&&Te!==a){$e();Te=a;Ve="";var c;c=0===b.indexOf("gtm.")?encodeURIComponent(b):"*";bf[a]="&e="+c+"&eid="+a;Se||(Se=u.setTimeout($e,500))}},gf=function(a,b,c){if(df&&!We[a]&&b){a!==Te&&($e(),Te=a);var d=String(b[ce.sa]||"").replace(/_/g,
"");0===d.indexOf("cvt")&&(d="cvt");var e=c+d;Ve=Ve?Ve+"."+e:"&tr="+e;Se||(Se=u.setTimeout($e,500));2022<=Ze().length&&$e()}};var hf={},jf=new ya,kf={},lf={},qf={name:"dataLayer",set:function(a,b){Za(mf(a,b),kf);nf()},get:function(a){return pf(a,2)},reset:function(){jf=new ya;kf={};nf()}},pf=function(a,b){if(2!=b){var c=jf.get(a);if(df){var d=rf(a);c!==d&&Ac("GTM",5)}return c}return rf(a)},rf=function(a,b,c){var d=a.split("."),e=!1,f=void 0;return e?f:tf(d)},tf=function(a){for(var b=kf,c=0;c<a.length;c++){if(null===b)return!1;if(void 0===b)break;b=b[a[c]]}return b};
var wf=function(a,b){lf.hasOwnProperty(a)||(jf.set(a,b),Za(mf(a,b),kf),nf())},mf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c},nf=function(a){Ba(lf,function(b,c){jf.set(b,c);Za(mf(b,void 0),kf);Za(mf(b,c),kf);a&&delete lf[b]})},xf=function(a,b,c){hf[a]=hf[a]||{};var d=1!==c?rf(b):jf.get(b);"array"===Wa(d)||"object"===Wa(d)?hf[a][b]=Za(d):hf[a][b]=d},yf=function(a,b){if(hf[a])return hf[a][b]};var zf=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Af={cl:["ecl"],customPixels:["nonGooglePixels"],ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Bf={cl:["ecl"],customPixels:["customScripts","html"],
ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Cf="google customPixels customScripts html nonGooglePixels nonGoogleScripts nonGoogleIframes".split(" ");
var Ef=function(a){var b=pf("gtm.whitelist");b&&Ac("GTM",9);var c=b&&Na(Fa(b),Af),d=pf("gtm.blacklist");d||(d=pf("tagTypeBlacklist"))&&Ac("GTM",3);
d?Ac("GTM",8):d=[];Df()&&(d=Fa(d),d.push("nonGooglePixels","nonGoogleScripts"));0<=va(Fa(d),"google")&&Ac("GTM",2);var e=d&&Na(Fa(d),Bf),f={};return function(h){var k=h&&h[ce.sa];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==f[k])return f[k];var l=Ke[k]||[],m=a(k);if(b){var n;if(n=m)a:{if(0>va(c,k))if(l&&0<l.length)for(var q=0;q<l.length;q++){if(0>
va(c,l[q])){Ac("GTM",11);n=!1;break a}}else{n=!1;break a}n=!0}m=n}var t=!1;if(d){var p=0<=va(e,k);if(p)t=p;else{var r=Aa(e,l||[]);r&&Ac("GTM",10);t=r}}var v=!m||t;v||!(0<=va(l,"sandboxedScripts"))||c&&-1!==va(c,"sandboxedScripts")||(v=Aa(e,Cf));return f[k]=v}},Df=function(){return zf.test(u.location&&u.location.hostname)};var Ff={Zf:function(a,b){b[ce.Bd]&&"string"===typeof a&&(a=1==b[ce.Bd]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(ce.Dd)&&null===a&&(a=b[ce.Dd]);b.hasOwnProperty(ce.Fd)&&void 0===a&&(a=b[ce.Fd]);b.hasOwnProperty(ce.Ed)&&!0===a&&(a=b[ce.Ed]);b.hasOwnProperty(ce.Cd)&&!1===a&&(a=b[ce.Cd]);return a}};var Gf={active:!0,isWhitelisted:function(){return!0}},Hf=function(a){var b=Ae.zones;!b&&a&&(b=Ae.zones=a());return b};var If=!1,Jf=0,Kf=[];function Lf(a){if(!If){var b=A.createEventObject,c="complete"==A.readyState,d="interactive"==A.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){If=!0;for(var e=0;e<Kf.length;e++)D(Kf[e])}Kf.push=function(){for(var f=0;f<arguments.length;f++)D(arguments[f]);return 0}}}function Mf(){if(!If&&140>Jf){Jf++;try{A.documentElement.doScroll("left"),Lf()}catch(a){u.setTimeout(Mf,50)}}}var Nf=function(a){If?a():Kf.push(a)};var Of={},Pf={},Qf=function(a,b,c,d){if(!Pf[a]||Ce[b]||"__zone"===b)return-1;var e={};Ya(d)&&(e=Za(d,e));e.id=c;e.status="timeout";return Pf[a].tags.push(e)-1},Rf=function(a,b,c,d){if(Pf[a]){var e=Pf[a].tags[b];e&&(e.status=c,e.executionTime=d)}};function Sf(a){for(var b=Of[a]||[],c=0;c<b.length;c++)b[c]();Of[a]={push:function(d){d(ze.o,Pf[a])}}}
var Vf=function(a,b,c){Pf[a]={tags:[]};ra(b)&&Tf(a,b);c&&u.setTimeout(function(){return Sf(a)},Number(c));return Uf(a)},Tf=function(a,b){Of[a]=Of[a]||[];Of[a].push(Ja(function(){return D(function(){b(ze.o,Pf[a])})}))};function Uf(a){var b=0,c=0,d=!1;return{add:function(){c++;return Ja(function(){b++;d&&b>=c&&Sf(a)})},Hf:function(){d=!0;b>=c&&Sf(a)}}};var Wf=function(){function a(d){return!ta(d)||0>d?0:d}if(!Ae._li&&u.performance&&u.performance.timing){var b=u.performance.timing.navigationStart,c=ta(qf.get("gtm.start"))?qf.get("gtm.start"):0;Ae._li={cst:a(c-b),cbt:a(Ge-b)}}};var $f=!1,ag=function(){return u.GoogleAnalyticsObject&&u[u.GoogleAnalyticsObject]},bg=!1;
var fg=function(){},eg=function(){return u.GoogleAnalyticsObject||"ga"},gg=!1;var ng=function(a){};function mg(a,b,c){b.containerId=ze.o;var d={type:a,value:b};c.length&&(d.trace=c);return d};function og(a,b,c,d){var e=Rd[a],f=pg(a,b,c,d);if(!f)return null;var h=Zd(e[ce.Ud],c,[]);if(h&&h.length){var k=h[0];f=og(k.index,{R:f,Y:1===k.fe?b.terminate:f,terminate:b.terminate},c,d)}return f}
function pg(a,b,c,d){function e(){if(f[ce.rf])k();else{var w=$d(f,c,[]),y=Qf(c.id,String(f[ce.sa]),Number(f[ce.Vd]),w[ce.sf]),x=!1;w.vtp_gtmOnSuccess=function(){if(!x){x=!0;var C=Ha()-B;gf(c.id,Rd[a],"5");Rf(c.id,y,"success",C);h()}};w.vtp_gtmOnFailure=function(){if(!x){x=!0;var C=Ha()-B;gf(c.id,Rd[a],"6");Rf(c.id,y,"failure",C);k()}};w.vtp_gtmTagId=f.tag_id;
w.vtp_gtmEventId=c.id;gf(c.id,f,"1");var z=function(C){var E=Ha()-B;ng(C);gf(c.id,f,"7");Rf(c.id,y,"exception",E);x||(x=!0,k())};var B=Ha();try{Yd(w,c)}catch(C){z(C)}}}var f=Rd[a],h=b.R,k=b.Y,l=b.terminate;if(c.Yc(f))return null;var m=Zd(f[ce.Wd],c,[]);if(m&&m.length){var n=m[0],q=og(n.index,{R:h,Y:k,terminate:l},c,d);if(!q)return null;h=q;k=2===n.fe?l:q}if(f[ce.Td]||f[ce.tf]){var t=f[ce.Td]?Sd:c.vh,p=h,r=k;if(!t[a]){e=Ja(e);var v=qg(a,t,e);h=v.R;k=v.Y}return function(){t[a](p,r)}}return e}
function qg(a,b,c){var d=[],e=[];b[a]=rg(d,e,c);return{R:function(){b[a]=sg;for(var f=0;f<d.length;f++)d[f]()},Y:function(){b[a]=tg;for(var f=0;f<e.length;f++)e[f]()}}}function rg(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function sg(a){a()}function tg(a,b){b()};var wg=function(a,b){for(var c=[],d=0;d<Rd.length;d++)if(a.nb[d]){var e=Rd[d];var f=b.add();try{var h=og(d,{R:f,Y:f,terminate:f},a,d);h?c.push({Me:d,b:ae(e),Qa:h}):(ug(d,a),f())}catch(l){f()}}b.Hf();c.sort(vg);for(var k=0;k<c.length;k++)c[k].Qa();return 0<c.length};function vg(a,b){var c,d=b.b,e=a.b;c=d>e?1:d<e?-1:0;var f;if(0!==c)f=c;else{var h=a.Me,k=b.Me;f=h>k?1:h<k?-1:0}return f}
function ug(a,b){if(!df)return;var c=function(d){var e=b.Yc(Rd[d])?"3":"4",f=Zd(Rd[d][ce.Ud],b,[]);f&&f.length&&c(f[0].index);gf(b.id,Rd[d],e);var h=Zd(Rd[d][ce.Wd],b,[]);h&&h.length&&c(h[0].index)};c(a);}
var xg=!1,yg=function(a,b,c,d,e){if("gtm.js"==b){if(xg)return!1;xg=!0}ff(a,b);var f=Vf(a,d,e);xf(a,"event",1);xf(a,"ecommerce",1);xf(a,"gtm");var h={id:a,name:b,Yc:Ef(c),nb:[],vh:[],xe:function(n){Ac("GTM",6);ng(n)}};h.nb=ke(h);var k=wg(h,f);"gtm.js"!==b&&"gtm.sync"!==b||fg();if(!k)return k;for(var l=0;l<h.nb.length;l++)if(h.nb[l]){var m=
Rd[l];if(m&&!Ce[String(m[ce.sa])])return!0}return!1};var H={wc:"event_callback",yc:"event_timeout"};var Ag={},Cg=function(a){var b=ze.o;return function(){var c=arguments[0];if(c&&(Ag[c]||Ag.all)){var d=a.apply(void 0,Array.prototype.slice.call(arguments,0));Ag[c]&&Bg(b,c,Ag[c],d);Ag.all&&Bg(b,c,Ag.all,d)}}};
function Bg(a,b,c,d){for(var e=0;e<c.length;e++){var f=void 0,h="An in-page policy denied the permission request";try{f=c[e].call(void 0,a,b,d),h+="."}catch(k){h="string"===typeof k?h+(": "+k):k instanceof Error?h+(": "+k.message):h+"."}if(!f)throw new de(b,{},h);}};var Dg=/[A-Z]+/,Eg=/\s/,Fg=function(a){if(sa(a)&&(a=Ga(a),!Eg.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(Dg.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],za:d}}}}},Hg=function(a){for(var b={},c=0;c<a.length;++c){var d=Fg(a[c]);d&&(b[d.id]=d)}Gg(b);var e=[];Ba(b,function(f,h){e.push(h)});return e};
function Gg(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];"AW"===d.prefix&&d.za[1]&&b.push(d.containerId)}for(var e=0;e<b.length;++e)delete a[b[e]]};var Ig=null,Jg={},Kg={},Lg,Mg=function(a,b){var c={event:a};b&&(c.eventModel=Za(b),b[H.wc]&&(c.eventCallback=b[H.wc]),b[H.yc]&&(c.eventTimeout=b[H.yc]));return c};
var Sg={config:function(a){},event:function(a){var b=a[1];if(sa(b)&&!(3<a.length)){var c;
if(2<a.length){if(!Ya(a[2]))return;c=a[2]}var d=Mg(b,c);return d}},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}},policy:function(a){if(3===a.length){var b=a[1],c=a[2];Ag[b]||(Ag[b]=[]);Ag[b].push(c)}},set:function(a){var b;2==a.length&&Ya(a[1])?b=Za(a[1]):3==a.length&&sa(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b.eventModel=Za(b),b.event="gtag.set",b._clear=!0,b}},Tg={policy:!0};var Ug=function(){var a=!1;return a};function Vg(a){Ua(this.getName(),["callback:!Fn"],arguments);Vc(this,"read_container_data");var b=this.i().Z;if(!b)throw Error("invalid program state");var c=b.eventId;ta(c)&&Tf(c,ab(a))}function Wg(a,b){Ua(this.getName(),["key:!string","dataLayerVersion:?number"],arguments);Vc(this,"read_data_layer",a);return $a(pf(a,b||2),this.i())}function Xg(){return(new Date).getTime()}function Yg(a){return Da(ab(a,this.i()))}function Zg(a){return null===a?"null":void 0===a?"undefined":a.toString()}
function $g(a,b){Ua(this.getName(),["min:!number","max:!number"],arguments);return xa(a,b)}function ah(a,b,c){Ua(this.getName(),["tableObj:!List","keyColumnName:!string","valueColumnName:!string"],arguments);for(var d=new Ra,e=!1,f=0;f<a.length();f++){var h=a.get(f);h instanceof Ra&&h.has(b)&&h.has(c)&&(d.set(h.get(b),h.get(c)),e=!0)}return e?d:null}function bh(){Vc(this,"read_character_set");return A.characterSet||""}function ch(){Vc(this,"read_title");return A.title||""}
var dh=function(){var a=new hc;Ug()?a.addAll({injectHiddenIframe:qa,injectScript:qa}):a.addAll({injectHiddenIframe:ed,injectScript:gd});var b=id;a.addAll({aliasInWindow:od,addEventCallback:Vg,callInWindow:Wc,callLater:Xc,copyFromDataLayer:Wg,copyFromWindow:Yc,createQueue:md,createArgumentsQueue:nd,encodeUri:qd,encodeUriComponent:rd,
generateRandom:$g,getCookieValues:Zc,getQueryParameters:cd,getReferrerQueryParameters:dd,getReferrerUrl:$c,getTimestamp:Xg,getUrl:ad,logToConsole:hd,makeInteger:Yg,makeString:Zg,makeTableMap:ah,queryPermission:pd,readCharacterSet:bh,readTitle:ch,sendPixel:b,setCookie:jd,setInWindow:kd});return function(c){var d=a.get(c);if(d)return d;throw Error(c+" is not a valid API name.");}};var eh;function fh(){var a=data.runtime||[],b=data.runtime_lines;eh=new gc;gh();Nd=function(e,f,h){hh(f);var k=new Ra;Ba(f,function(m,n){k.set(m,$a(n))});eh.Fa(ge());var l=eh.hc({Jf:ih[e]||jh,eventId:void 0!==h?h.id:void 0},[e,k]);eh.Fa(void 0);l instanceof ha&&"return"===l.K&&(l=l.getData());return ab(l)};eh.va("require",dh());for(var c=0;c<a.length;c++){var d=a[c];if(!ua(d)||3>d.length){if(0===d.length)continue;break}b&&b[c]&&b[c].length&&ee(d,b[c]);eh.Qa(d)}}
function hh(a){var b=a.gtmOnSuccess,c=a.gtmOnFailure;ra(b)&&(a.gtmOnSuccess=function(){D(b)});ra(c)&&(a.gtmOnFailure=function(){D(c)})}var ih={};function jh(a){throw kh(a,{},"The requested permission is not configured.");}
function lh(a){var b={},c=Cg(function(){var d=arguments[0];return d&&b[d]?b[d].apply(void 0,Array.prototype.slice.call(arguments,0)):{}});Ba(a,function(d,e){var f={};Ba(e,function(h,k){var l,m=Xd(h,k);m.vtp_permissionName=h;m.vtp_createPermissionError=kh;l=Yd(m);f[h]=l.assert;b[h]||(b[h]=l.M)});ih[d]=function(h,k){var l=f[h]||jh,m=Array.prototype.slice.call(arguments,0);l.apply(void 0,m);c.apply(void 0,m)}})}function kh(a,b,c){return new de(a,b,c)}
function gh(){var a=eh;Ae.SANDBOXED_JS_SEMAPHORE=Ae.SANDBOXED_JS_SEMAPHORE||0;a.oa(function(b,c,d){Ae.SANDBOXED_JS_SEMAPHORE++;try{return b.apply(c,d)}finally{Ae.SANDBOXED_JS_SEMAPHORE--}})};var nh=function(a){return mh?A.querySelectorAll(a):null},oh=function(a,b){if(!mh)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!A.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);
return null},ph=!1;if(A.querySelectorAll)try{var qh=A.querySelectorAll(":root");qh&&1==qh.length&&qh[0]==A.documentElement&&(ph=!0)}catch(a){}var mh=ph;var xh=function(a){if(wh(a))return a;this.Ch=a};xh.prototype.ug=function(){return this.Ch};var wh=function(a){return!a||"object"!==Wa(a)||Ya(a)?!1:"getUntrustedUpdateValue"in a};xh.prototype.getUntrustedUpdateValue=xh.prototype.ug;var yh=!1,zh=[];function Ah(){if(!yh){yh=!0;for(var a=0;a<zh.length;a++)D(zh[a])}}var Bh=function(a){yh?D(a):zh.push(a)};var Ch=[],Dh=!1,Eh=function(a){return u["dataLayer"].push(a)},Fh=function(a){var b=Ae["dataLayer"],c=b?b.subscribers:1,d=0;return function(){++d===c&&a()}},Hh=function(a){var b=a._clear;Ba(a,function(f,h){"_clear"!==f&&(b&&wf(f,void 0),wf(f,h))});Fe||(Fe=a["gtm.start"]);var c=a.event;if(!c)return!1;var d=a["gtm.uniqueEventId"];d||(d=Le(),a["gtm.uniqueEventId"]=d,wf("gtm.uniqueEventId",d));He=c;var e=Gh(a);
He=null;return e};function Gh(a){var b=a.event,c=a["gtm.uniqueEventId"],d,e=Ae.zones;d=e?e.checkState(ze.o,c):Gf;return d.active?yg(c,b,d.isWhitelisted,a.eventCallback,a.eventTimeout)?!0:!1:!1}
var Ih=function(){for(var a=!1;!Dh&&0<Ch.length;){Dh=!0;delete kf.eventModel;nf();var b=Ch.shift();if(null!=b){var c=wh(b);if(c){var d=b;b=wh(d)?d.getUntrustedUpdateValue():void 0;for(var e=["gtm.whitelist","gtm.blacklist","tagTypeBlacklist"],f=0;f<e.length;f++){var h=e[f],k=pf(h,1);if(ua(k)||Ya(k))k=Za(k);lf[h]=k}}try{if(ra(b))try{b.call(qf)}catch(r){}else if(ua(b)){var l=b;if(sa(l[0])){var m=
l[0].split("."),n=m.pop(),q=l.slice(1),t=pf(m.join("."),2);if(void 0!==t&&null!==t)try{t[n].apply(t,q)}catch(r){}}}else{if(Ca(b)){a:{if(b.length&&sa(b[0])){var p=Sg[b[0]];if(p&&(!c||!Tg[b[0]])){b=p(b);break a}}b=void 0}if(!b){Dh=!1;continue}}a=Hh(b)||a}}finally{c&&nf(!0)}}Dh=!1}return!a},Jh=function(){var a=Ih();try{var b=ze.o,c=u["dataLayer"].hide;if(c&&void 0!==c[b]&&c.end){c[b]=
!1;var d=!0,e;for(e in c)if(c.hasOwnProperty(e)&&!0===c[e]){d=!1;break}d&&(c.end(),c.end=null)}}catch(f){}return a},Kh=function(){var a=lc("dataLayer",[]),b=lc("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};Nf(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Bh(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});b.subscribers=(b.subscribers||0)+1;var c=a.push;a.push=function(){var d;if(0<Ae.SANDBOXED_JS_SEMAPHORE){d=[];for(var e=0;e<arguments.length;e++)d[e]=
new xh(arguments[e])}else d=[].slice.call(arguments,0);var f=c.apply(a,d);Ch.push.apply(Ch,d);if(300<this.length)for(Ac("GTM",4);300<this.length;)this.shift();var h="boolean"!==typeof f||f;return Ih()&&h};Ch.push.apply(Ch,a.slice(0));D(Jh)};var Lh;var hi={};hi.Kb=new String("undefined");
var ii=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===hi.Kb?b:a[d]);return c.join("")}};ii.prototype.toString=function(){return this.resolve("undefined")};ii.prototype.valueOf=ii.prototype.toString;hi.uf=ii;hi.Ic={};hi.bg=function(a){return new ii(a)};var ji={};hi.kh=function(a,b){var c=Le();ji[c]=[a,b];return c};hi.ce=function(a){var b=a?0:1;return function(c){var d=ji[c];if(d&&"function"===typeof d[b])d[b]();ji[c]=void 0}};hi.Ig=function(a){for(var b=!1,c=!1,
d=2;d<a.length;d++)b=b||8===a[d],c=c||16===a[d];return b&&c};hi.Yg=function(a){if(a===hi.Kb)return a;var b=Le();hi.Ic[b]=a;return'google_tag_manager["'+ze.o+'"].macro('+b+")"};hi.Mg=function(a,b,c){a instanceof hi.uf&&(a=a.resolve(hi.kh(b,c)),b=qa);return{Vc:a,R:b}};var ki=function(a,b,c){function d(f,h){var k=f[h];return k}var e={event:b,"gtm.element":a,"gtm.elementClasses":d(a,"className"),"gtm.elementId":a["for"]||tc(a,"id")||"","gtm.elementTarget":a.formTarget||d(a,"target")||""};c&&(e["gtm.triggers"]=c.join(","));e["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||d(a,"href")||a.src||a.code||a.codebase||
"";return e},li=function(a){Ae.hasOwnProperty("autoEventsSettings")||(Ae.autoEventsSettings={});var b=Ae.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},mi=function(a,b,c){li(a)[b]=c},ni=function(a,b,c,d){var e=li(a),f=Ia(e,b,d);e[b]=c(f)},oi=function(a,b,c){var d=li(a);return Ia(d,b,c)};var pi=function(){for(var a=ic.userAgent+(A.cookie||"")+(A.referrer||""),b=a.length,c=u.history.length;0<c;)a+=c--^b++;var d=1,e,f,h;if(a)for(d=0,f=a.length-1;0<=f;f--)h=a.charCodeAt(f),d=(d<<6&268435455)+h+(h<<14),e=d&266338304,d=0!=e?d^e>>21:d;return[Math.round(2147483647*Math.random())^d&2147483647,Math.round(Ha()/1E3)].join(".")},si=function(a,b,c,d){var e=qi(b);return Mc(a,e,ri(c),d)},qi=function(a){if(!a)return 1;a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length},ri=function(a){if(!a||
"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1};function ti(a,b){var c=""+qi(a),d=ri(b);1<d&&(c+="-"+d);return c};var ui=["1"],vi={},zi=function(a,b,c,d){var e=wi(a);vi[e]||xi(e,b,c)||(yi(e,pi(),b,c,d),xi(e,b,c))};function yi(a,b,c,d,e){var f;f=["1",ti(d,c),b].join(".");Rc(a,f,c,d,0==e?void 0:new Date(Ha()+1E3*(void 0==e?7776E3:e)))}function xi(a,b,c){var d=si(a,b,c,ui);d&&(vi[a]=d);return d}function wi(a){return(a||"_gcl")+"_au"};var Ai=function(){for(var a=[],b=A.cookie.split(";"),c=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,d=0;d<b.length;d++){var e=b[d].match(c);e&&a.push({td:e[1],value:e[2]})}var f={};if(!a||!a.length)return f;for(var h=0;h<a.length;h++){var k=a[h].value.split(".");"1"==k[0]&&3==k.length&&k[1]&&(f[a[h].td]||(f[a[h].td]=[]),f[a[h].td].push({timestamp:k[1],og:k[2]}))}return f};function Bi(){for(var a=Ci,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function Di(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}
var Ci,Ei,Fi=function(a){Ci=Ci||Di();Ei=Ei||Bi();for(var b=[],c=0;c<a.length;c+=3){var d=c+1<a.length,e=c+2<a.length,f=a.charCodeAt(c),h=d?a.charCodeAt(c+1):0,k=e?a.charCodeAt(c+2):0,l=f>>2,m=(f&3)<<4|h>>4,n=(h&15)<<2|k>>6,q=k&63;e||(q=64,d||(n=64));b.push(Ci[l],Ci[m],Ci[n],Ci[q])}return b.join("")},Gi=function(a){function b(l){for(;d<a.length;){var m=a.charAt(d++),n=Ei[m];if(null!=n)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return l}Ci=Ci||Di();Ei=Ei||
Bi();for(var c="",d=0;;){var e=b(-1),f=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|f>>4);64!=h&&(c+=String.fromCharCode(f<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var Hi;function Ii(a,b){if(!a||b===A.location.hostname)return!1;for(var c=0;c<a.length;c++)if(a[c]instanceof RegExp){if(a[c].test(b))return!0}else if(0<=b.indexOf(a[c]))return!0;return!1}
var Mi=function(){var a=Ji,b=Ki,c=Li(),d=function(h){a(h.target||h.srcElement||{})},e=function(h){b(h.target||h.srcElement||{})};if(!c.init){rc(A,"mousedown",d);rc(A,"keyup",d);rc(A,"submit",e);var f=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(){b(this);f.call(this)};c.init=!0}},Li=function(){var a=lc("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var Ni=/(.*?)\*(.*?)\*(.*)/,Oi=/^https?:\/\/([^\/]*?)\.?cdn\.ampproject\.org\/?(.*)/,Pi=/^(?:www\.|m\.|amp\.)+/,Qi=/([^?#]+)(\?[^#]*)?(#.*)?/,Ri=/(.*?)(^|&)_gl=([^&]*)&?(.*)/,Ti=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()&&(b.push(c),b.push(Fi(String(d))))}var e=b.join("*");return["1",Si(e),e].join("*")},Si=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||
window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:b),a].join("*"),d;if(!(d=Hi)){for(var e=Array(256),f=0;256>f;f++){for(var h=f,k=0;8>k;k++)h=h&1?h>>>1^3988292384:h>>>1;e[f]=h}d=e}Hi=d;for(var l=4294967295,m=0;m<c.length;m++)l=l>>>8^Hi[(l^c.charCodeAt(m))&255];return((l^-1)>>>0).toString(36)},Vi=function(){return function(a){var b=Ic(u.location.href),c=b.search.replace("?",""),d=Dc(c,"_gl",!1,!0)||"";a.query=Ui(d)||{};var e=Gc(b,"fragment").match(Ri);a.fragment=Ui(e&&
e[3]||"")||{}}},Ui=function(a){var b;b=void 0===b?3:b;try{if(a){var c;a:{for(var d=a,e=0;3>e;++e){var f=Ni.exec(d);if(f){c=f;break a}d=decodeURIComponent(d)}c=void 0}var h=c;if(h&&"1"===h[1]){var k=h[3],l;a:{for(var m=h[2],n=0;n<b;++n)if(m===Si(k,n)){l=!0;break a}l=!1}if(l){for(var q={},t=k?k.split("*"):[],p=0;p<t.length;p+=2)q[t[p]]=Gi(t[p+1]);return q}}}}catch(r){}};
function Wi(a,b,c){function d(m){var n=m,q=Ri.exec(n),t=n;if(q){var p=q[2],r=q[4];t=q[1];r&&(t=t+p+r)}m=t;var v=m.charAt(m.length-1);m&&"&"!==v&&(m+="&");return m+l}c=void 0===c?!1:c;var e=Qi.exec(b);if(!e)return"";var f=e[1],h=e[2]||"",k=e[3]||"",l="_gl="+a;c?k="#"+d(k.substring(1)):h="?"+d(h.substring(1));return""+f+h+k}
function Xi(a,b,c){for(var d={},e={},f=Li().decorators,h=0;h<f.length;++h){var k=f[h];(!c||k.forms)&&Ii(k.domains,b)&&(k.fragment?La(e,k.callback()):La(d,k.callback()))}if(Ma(d)){var l=Ti(d);if(c){if(a&&a.action){var m=(a.method||"").toLowerCase();if("get"===m){for(var n=a.childNodes||[],q=!1,t=0;t<n.length;t++){var p=n[t];if("_gl"===p.name){p.setAttribute("value",l);q=!0;break}}if(!q){var r=A.createElement("input");r.setAttribute("type","hidden");r.setAttribute("name","_gl");r.setAttribute("value",
l);a.appendChild(r)}}else if("post"===m){var v=Wi(l,a.action);yc.test(v)&&(a.action=v)}}}else Yi(l,a,!1)}if(!c&&Ma(e)){var w=Ti(e);Yi(w,a,!0)}}function Yi(a,b,c){if(b.href){var d=Wi(a,b.href,void 0===c?!1:c);yc.test(d)&&(b.href=d)}}
var Ji=function(a){try{var b;a:{for(var c=a,d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var f=e.protocol;"http:"!==f&&"https:"!==f||Xi(e,e.hostname,!1)}}catch(h){}},Ki=function(a){try{if(a.action){var b=Gc(Ic(a.action),"host");Xi(a,b,!0)}}catch(c){}},Zi=function(a,b,c,d){Mi();var e={callback:a,domains:b,fragment:"fragment"===c,forms:!!d};Li().decorators.push(e)},$i=function(){var a=A.location.hostname,b=Oi.exec(A.referrer);if(!b)return!1;
var c=b[2],d=b[1],e="";if(c){var f=c.split("/"),h=f[1];e="s"===h?decodeURIComponent(f[2]):decodeURIComponent(h)}else if(d){if(0===d.indexOf("xn--"))return!1;e=d.replace(/-/g,".").replace(/\.\./g,"-")}return a.replace(Pi,"")===e.replace(Pi,"")},aj=function(a,b){return!1===a?!1:a||b||$i()};var bj={};var cj=/^\w+$/,dj=/^[\w-]+$/,ej=/^~?[\w-]+$/,fj={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha"};function gj(a){return a&&"string"==typeof a&&a.match(cj)?a:"_gcl"}var ij=function(){var a=Ic(u.location.href),b=Gc(a,"query",!1,void 0,"gclid"),c=Gc(a,"query",!1,void 0,"gclsrc"),d=Gc(a,"query",!1,void 0,"dclid");if(!b||!c){var e=a.hash.replace("#","");b=b||Dc(e,"gclid",!1,void 0);c=c||Dc(e,"gclsrc",!1,void 0)}return hj(b,c,d)};
function hj(a,b,c){var d={},e=function(f,h){d[h]||(d[h]=[]);d[h].push(f)};if(void 0!==a&&a.match(dj))switch(b){case void 0:e(a,"aw");break;case "aw.ds":e(a,"aw");e(a,"dc");break;case "ds":e(a,"dc");break;case "3p.ds":(void 0==bj.gtm_3pds?0:bj.gtm_3pds)&&e(a,"dc");break;case "gf":e(a,"gf");break;case "ha":e(a,"ha")}c&&e(c,"dc");return d}
function jj(a,b,c){function d(q,t){var p=kj(q,e);p&&Rc(p,t,h,f,l,!0)}b=b||{};var e=gj(b.prefix),f=b.domain||"auto",h=b.path||"/",k=void 0==b.ye?7776E3:b.ye;c=c||Ha();var l=0==k?void 0:new Date(c+1E3*k),m=Math.round(c/1E3),n=function(q){return["GCL",m,q].join(".")};a.aw&&(!0===b.ji?d("aw",n("~"+a.aw[0])):d("aw",n(a.aw[0])));a.dc&&d("dc",n(a.dc[0]));a.gf&&d("gf",n(a.gf[0]));a.ha&&d("ha",n(a.ha[0]))}
var kj=function(a,b){var c=fj[a];if(void 0!==c)return b+c},lj=function(a){var b=a.split(".");return 3!==b.length||"GCL"!==b[0]?0:1E3*(Number(b[1])||0)};function mj(a){var b=a.split(".");if(3==b.length&&"GCL"==b[0]&&b[1])return b[2]}
var nj=function(a,b,c,d,e){if(ua(b)){var f=gj(e);Zi(function(){for(var h={},k=0;k<a.length;++k){var l=kj(a[k],f);if(l){var m=Jc(l,A.cookie);m.length&&(h[l]=m.sort()[m.length-1])}}return h},b,c,d)}},oj=function(a){return a.filter(function(b){return ej.test(b)})},pj=function(a){for(var b=["aw","dc"],c=gj(a&&a.prefix),d={},e=0;e<b.length;e++)fj[b[e]]&&(d[b[e]]=fj[b[e]]);Ba(d,function(f,h){var k=Jc(c+h,A.cookie);if(k.length){var l=k[0],m=lj(l),n={};n[f]=[mj(l)];jj(n,a,m)}})};var qj=/^\d+\.fls\.doubleclick\.net$/;function rj(a){var b=Ic(u.location.href),c=Gc(b,"host",!1);if(c&&c.match(qj)){var d=Gc(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function sj(a,b){if("aw"==a||"dc"==a){var c=rj("gcl"+a);if(c)return c.split(".")}var d=gj(b);if("_gcl"==d){var e;e=ij()[a]||[];if(0<e.length)return e}var f=kj(a,d),h;if(f){var k=[];if(A.cookie){var l=Jc(f,A.cookie);if(l&&0!=l.length){for(var m=0;m<l.length;m++){var n=mj(l[m]);n&&-1===va(k,n)&&k.push(n)}h=oj(k)}else h=k}else h=k}else h=[];return h}
var tj=function(){var a=rj("gac");if(a)return decodeURIComponent(a);var b=Ai(),c=[];Ba(b,function(d,e){for(var f=[],h=0;h<e.length;h++)f.push(e[h].og);f=oj(f);f.length&&c.push(d+":"+f.join(","))});return c.join(";")},uj=function(a,b,c,d,e){zi(b,c,d,e);var f=vi[wi(b)],h=ij().dc||[],k=!1;if(f&&0<h.length){var l=Ae.joined_au=Ae.joined_au||{},m=b||"_gcl";if(!l[m])for(var n=0;n<h.length;n++){var q="https://adservice.google.com/ddm/regclk",t=q=q+"?gclid="+h[n]+"&auiddc="+f;ic.sendBeacon&&ic.sendBeacon(t)||qc(t);k=l[m]=
!0}}null==a&&(a=k);if(a&&f){var p=wi(b),r=vi[p];r&&yi(p,r,c,d,e)}};var vj;if(3===ze.Ob.length)vj="g";else{var wj="G";vj=wj}
var xj={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:vj,OPT:"o"},yj=function(a){var b=ze.o.split("-"),c=b[0].toUpperCase(),d=xj[c]||"i",e=a&&"GTM"===c?b[1]:"OPT"===c?b[1]:"",f;if(3===ze.Ob.length){var h=void 0;f="2"+(h||"w")}else f=
"";return f+d+ze.Ob+e};var Dj=["input","select","textarea"],Ej=["button","hidden","image","reset","submit"],Fj=function(a){var b=a.tagName.toLowerCase();return!wa(Dj,function(c){return c===b})||"input"===b&&wa(Ej,function(c){return c===a.type.toLowerCase()})?!1:!0};var Ij=!!u.MutationObserver,Jj=void 0,Kj=function(a){if(!Jj){var b=function(){var c=A.body;if(c)if(Ij)(new MutationObserver(function(){for(var e=0;e<Jj.length;e++)D(Jj[e])})).observe(c,{childList:!0,subtree:!0});else{var d=!1;rc(c,"DOMNodeInserted",function(){d||(d=!0,D(function(){d=!1;for(var e=0;e<Jj.length;e++)D(Jj[e])}))})}};Jj=[];A.body?b():D(b)}Jj.push(a)};
var Nj=function(a,b){return a.length&&b.length&&a.lastIndexOf(b)===a.length-b.length},Oj=function(a,b){var c="*"===b.charAt(b.length-1)||"/"===b||"/*"===b;Nj(b,"/*")&&(b=b.slice(0,-2));Nj(b,"?")&&(b=b.slice(0,-1));var d=b.split("*");if(!c&&1===d.length)return a===d[0];for(var e=-1,f=0;f<d.length;f++){var h=d[f];if(h){e=a.indexOf(h,e);if(-1===e||0===f&&0!==e)return!1;e+=h.length}}if(c||e===a.length)return!0;var k=d[d.length-1];return a.lastIndexOf(k)===a.length-k.length},Pj=/^[a-z0-9-]+$/i,Qj=/^https:\/\/(\*\.|)((?:[a-z0-9-]+\.)+[a-z0-9-]+)\/(.*)$/i,
Rj=function(a,b){for(var c=0;c<b.length;c++){var d;var e=a,f=b[c];if(!Qj.exec(f))throw Error("Invalid Wildcard");var h=Ic(e),k;if(!(k="https:"!=h.protocol||h.port&&"443"!=h.port)){var l;b:{var m=h.hostname.split(".");if(2>m.length)l=!1;else{for(var n=0;n<m.length;n++)if(!Pj.exec(m[n])){l=!1;break b}l=!0}}k=!l}if(k)d=!1;else{var q=f.slice(8),t=q.slice(0,q.indexOf("/")),p;var r=h.hostname,v=t;if(0!==v.indexOf("*."))p=r.toLowerCase()===v.toLowerCase();else{v=v.slice(2);var w=r.toLowerCase().indexOf(v.toLowerCase());
p=-1===w?!1:r.length===v.length?!0:r.length!==v.length+w?!1:"."===r[w-1]}if(p){var y=q.slice(q.indexOf("/"));d=Oj(h.pathname+h.search,y)?!0:!1}else d=!1}if(d)return!0}return!1};var mk=u.clearTimeout,nk=u.setTimeout,K=function(a,b,c){if(Ug()){b&&D(b)}else return nc(a,b,c)},ok=function(){return new Date},pk=function(){return u.location.href},qk=function(a){return Gc(Ic(a),"fragment")},rk=function(a){return Hc(Ic(a))},sk=null;
var tk=function(a,b){return pf(a,b||2)},uk=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return Eh(a)},vk=function(a,b){u[a]=b},L=function(a,b,c){b&&(void 0===u[a]||c&&!u[a])&&(u[a]=b);return u[a]},wk=function(a,b,c){return Jc(a,b,void 0===c?!0:!!c)},xk=function(a,b,c,d){var e={prefix:a,path:b,domain:c,ye:d},f=ij();jj(f,e);pj(e)},yk=function(a,b,c,d,e){var f=Vi(),h=Li();h.data||(h.data={query:{},fragment:{}},f(h.data));var k={},l=h.data;l&&
(La(k,l.query),La(k,l.fragment));for(var m=gj(b),n=0;n<a.length;++n){var q=a[n];if(void 0!==fj[q]){var t=kj(q,m),p=k[t];if(p){var r=Math.min(lj(p),Ha()),v;b:{for(var w=r,y=Jc(t,A.cookie),x=0;x<y.length;++x)if(lj(y[x])>w){v=!0;break b}v=!1}v||Rc(t,p,c,d,0==e?void 0:new Date(r+1E3*(null==e?7776E3:e)),!0)}}}var z={prefix:b,path:c,domain:d};jj(hj(k.gclid,k.gclsrc),z);},zk=function(a,b,c,d,e){nj(a,b,c,d,e);},
Ak=function(a,b){if(Ug()){b&&D(b)}else pc(a,b)},Bk=function(a){return!!oi(a,"init",!1)},Ck=function(a){mi(a,"init",!0)},Dk=function(a,b,c){var d=(void 0===c?0:c)?"www.googletagmanager.com/gtag/js":Ee;d+="?id="+encodeURIComponent(a)+"&l=dataLayer";b&&Ba(b,function(e,f){f&&(d+="&"+e+"="+encodeURIComponent(f))});K(G("https://","http://",d))},Ek=function(a,b){var c=a[b];return c};
var Gk=hi.Mg;var Hk=new ya,Ik=function(a,b){function c(h){var k=Ic(h),l=Gc(k,"protocol"),m=Gc(k,"host",!0),n=Gc(k,"port"),q=Gc(k,"path").toLowerCase().replace(/\/$/,"");if(void 0===l||"http"==l&&"80"==n||"https"==l&&"443"==n)l="web",n="default";return[l,m,n,q]}for(var d=c(String(a)),e=c(String(b)),f=0;f<d.length;f++)if(d[f]!==e[f])return!1;return!0},Jk=function(a){var b=a.arg0,c=a.arg1;if(a.any_of&&ua(c)){for(var d=0;d<c.length;d++)if(Jk({"function":a["function"],arg0:b,arg1:c[d]}))return!0;return!1}switch(a["function"]){case "_cn":return 0<=
String(b).indexOf(String(c));case "_css":var e;a:{if(b){var f=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var h=0;h<f.length;h++)if(b[f[h]]){e=b[f[h]](c);break a}}catch(v){}}e=!1}return e;case "_ew":var k,l;k=String(b);l=String(c);var m=k.length-l.length;return 0<=m&&k.indexOf(l,m)==m;case "_eq":return String(b)==String(c);case "_ge":return Number(b)>=Number(c);case "_gt":return Number(b)>Number(c);case "_lc":var n;n=String(b).split(",");
return 0<=va(n,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":var q;var t=a.ignore_case?"i":void 0;try{var p=String(c)+t,r=Hk.get(p);r||(r=new RegExp(c,t),Hk.set(p,r));q=r.test(b)}catch(v){q=!1}return q;case "_sw":return 0==String(b).indexOf(String(c));case "_um":return Ik(b,c)}return!1};var Lk=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var Mk={},Nk=encodeURI,Y=encodeURIComponent,Ok=qc;var Pk=function(a,b){if(!a)return!1;var c=Gc(Ic(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var Qk=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};Mk.Jg=function(){var a=!1;return a};var Rk=function(){var a=!1;return a};var ql=function(){var a=u.gaGlobal=u.gaGlobal||{};a.hid=a.hid||xa();return a.hid};var Il=function(a,b,c,d){this.n=a;this.t=b;this.p=c;this.d=d},Jl=function(){this.c=1;this.e=[];this.p=null};function Kl(a){var b=Ae,c=b.gss=b.gss||{};return c[a]=c[a]||new Jl}var Ll=function(a,b){Kl(a).p=b},Ml=function(a){var b=Kl(a),c=b.p;if(c){var d=b.e,e=[];b.e=[];var f=function(h){for(var k=0;k<h.length;k++)try{var l=h[k];l.d?(l.d=!1,e.push(l)):c(l.n,l.t,l.p)}catch(m){}};f(d);f(e)}};var Wl=window,Xl=document,Yl=function(a){var b=Wl._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===Wl["ga-disable-"+a])return!0;try{var c=Wl.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(f){}for(var d=Jc("AMP_TOKEN",Xl.cookie,!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return Xl.getElementById("__gaOptOutExtension")?!0:!1};var em=function(a,b,c){dm(a);var d=Math.floor(Ha()/1E3);Kl(a).e.push(new Il(b,d,c,void 0));Ml(a)},fm=function(a,b,c){dm(a);var d=Math.floor(Ha()/1E3);Kl(a).e.push(new Il(b,d,c,!0))},dm=function(a){if(1===Kl(a).c&&(Kl(a).c=2,!Ug())){var b=encodeURIComponent(a);nc(("http:"!=u.location.protocol?"https:":"http:")+("//www.googletagmanager.com/gtag/js?id="+b+"&l=dataLayer&cx=c"))}},hm=function(a,b){},gm=function(a,
b){};var Z={a:{}};



Z.a.e=["google"],function(){(function(a){Z.__e=a;Z.__e.g="e";Z.__e.h=!0;Z.__e.b=0})(function(a){return String(yf(a.vtp_gtmEventId,"event"))})}();Z.a.f=["google"],function(){(function(a){Z.__f=a;Z.__f.g="f";Z.__f.h=!0;Z.__f.b=0})(function(a){var b=tk("gtm.referrer",1)||A.referrer;return b?a.vtp_component&&"URL"!=a.vtp_component?Gc(Ic(String(b)),a.vtp_component,a.vtp_stripWww,a.vtp_defaultPages,a.vtp_queryKey):rk(String(b)):String(b)})}();

Z.a.access_globals=["google"],function(){function a(b,c,d){var e={key:d,read:!1,write:!1,execute:!1};switch(c){case "read":e.read=!0;break;case "write":e.write=!0;break;case "readwrite":e.read=e.write=!0;break;case "execute":e.execute=!0;break;default:throw Error("Invalid access_globals request "+c);}return e}(function(b){Z.__access_globals=b;Z.__access_globals.g="access_globals";Z.__access_globals.h=!0;Z.__access_globals.b=0})(function(b){for(var c=b.vtp_keys||[],d=b.vtp_createPermissionError,e=
[],f=[],h=[],k=0;k<c.length;k++){var l=c[k],m=l.key;l.read&&e.push(m);l.write&&f.push(m);l.execute&&h.push(m)}return{assert:function(n,q,t){if(!sa(t))throw d(n,{},"Key must be a string.");if("read"===q){if(-1<va(e,t))return}else if("write"===q){if(-1<va(f,t))return}else if("readwrite"===q){if(-1<va(f,t)&&-1<va(e,t))return}else if("execute"===q){if(-1<va(h,t))return}else throw d(n,{},"Operation must be either 'read', 'write', or 'execute', was "+q);throw d(n,{},"Prohibited "+q+" on global variable: "+
t+".");},M:a}})}();
Z.a.u=["google"],function(){var a=function(b){return{toString:function(){return b}}};(function(b){Z.__u=b;Z.__u.g="u";Z.__u.h=!0;Z.__u.b=0})(function(b){var c;c=(c=b.vtp_customUrlSource?b.vtp_customUrlSource:tk("gtm.url",1))||pk();var d=b[a("vtp_component")];if(!d||"URL"==d)return rk(String(c));var e=Ic(String(c)),f;if("QUERY"===d)a:{var h=b[a("vtp_multiQueryKeys").toString()],k=b[a("vtp_queryKey").toString()]||"",l=b[a("vtp_ignoreEmptyQueryParam").toString()],m;m=h?ua(k)?k:String(k).replace(/\s+/g,
"").split(","):[String(k)];for(var n=0;n<m.length;n++){var q=Gc(e,"QUERY",void 0,void 0,m[n]);if(void 0!=q&&(!l||""!==q)){f=q;break a}}f=void 0}else f=Gc(e,d,"HOST"==d?b[a("vtp_stripWww")]:void 0,"PATH"==d?b[a("vtp_defaultPages")]:void 0,void 0);return f})}();

Z.a.inject_script=["google"],function(){function a(b,c){return{url:c}}(function(b){Z.__inject_script=b;Z.__inject_script.g="inject_script";Z.__inject_script.h=!0;Z.__inject_script.b=0})(function(b){var c=b.vtp_urls||[],d=b.vtp_createPermissionError;return{assert:function(e,f){if(!sa(f))throw d(e,{},"Script URL must be a string.");try{if(Rj(f,c))return}catch(h){throw d(e,{},"Invalid script URL filter.");}throw d(e,{},"Prohibited script URL: "+f);},M:a}})}();


Z.a.gclidw=["google"],function(){var a=["aw","dc","gf","ha"];(function(b){Z.__gclidw=b;Z.__gclidw.g="gclidw";Z.__gclidw.h=!0;Z.__gclidw.b=100})(function(b){D(b.vtp_gtmOnSuccess);var c,d,e;b.vtp_enableCookieOverrides&&(e=b.vtp_cookiePrefix,c=b.vtp_path,d=b.vtp_domain);var f=null;b.vtp_enableCookieUpdateFeature&&(f=!0,void 0!==b.vtp_cookieUpdate&&(f=!!b.vtp_cookieUpdate));var h=e,k=c,l=d;b.vtp_enableCrossDomainFeature&&(b.vtp_enableCrossDomain&&!1===b.vtp_acceptIncoming||(b.vtp_enableCrossDomain||$i())&&
yk(a,h,k,l));xk(e,c,d);uj(f,e,c,d);var m=e;if(b.vtp_enableCrossDomainFeature&&b.vtp_enableCrossDomain&&b.vtp_linkerDomains){var n=b.vtp_linkerDomains.toString().replace(/\s+/g,"").split(",");zk(a,n,b.vtp_urlPosition,!!b.vtp_formDecoration,m)}})}();Z.a.pntr=["nonGoogleScripts"];
Z.a.ga=["google"],function(){var a,b,c=function(d){function e(I){var J=[].slice.call(arguments,0);J[0]=v+J[0];p.push(J)}function f(I,J){void 0!==d[J]&&e(I,d[J])}function h(I,J){void 0!==d[J]&&e(I,Number(d[J]))}function k(I,J){if(t(J))for(var Q=0;Q<J.length;Q++)e(I,J[Q])}function l(I,J,Q){if(t(J))for(var S=0;S<J.length;S++){for(var X=[I],W=J[S],ja=0;ja<Q.length;ja++)X.push(W[Q[ja]]);e.apply(this,X)}}function m(I,J){void 0!==d[J]&&e("_set",I,d[J])}function n(I,J){return void 0===J?J:I(J)}function q(I,
J){void 0!==J&&(w+="&"+I+"="+J)}var t=ua,p=L("_gaq",[],!1),r=!1,v="";void 0==d.vtp_trackerName?v="gtm"+Le()+".":""!==d.vtp_trackerName&&(v=d.vtp_trackerName+".");f("_setAccount","vtp_webPropertyId");e("_set","gtmid",yj(!0));
f("_setAllowLinker","vtp_allowLinker");f("_setAllowAnchor","vtp_allowAnchor");
f("_setAllowHash","vtp_allowHash");k("_addIgnoredRef",d.vtp_ignoredRef);
k("_addIgnoredOrganic",d.vtp_ignoredOrganic);
var w="";

if(""!==w){var y=function(I,J,Q){for(var S=J.length-1;0<=S;S--){var X=J[S].split("=");if(X[0]===I)return X[1]||"1"}for(var W=Q.length-1;0<=W;W--){var ja=Q[W].split("=");if(ja[0]===I)return ja[1]||"1"}},x=Ic(pk()),z=Gc(x,"query").split("&"),B=d.vtp_allowAnchor?Gc(x,"fragment").split("&"):[];q("gclid",y("gclid",B,z));q("gclsrc",y("gclsrc",B,z));q("dclid",y("dclid",B,z));e("_set","campaignParams",w)}m("anonymizeIp","vtp_anonymizeIp");
d.vtp_enableInPageLinkId&&e("_require","inpage_linkid","//www.google-analytics.com/plugins/ga/inpage_linkid.js");f("_setCampaignTrack",
"vtp_campaignTrack");f("_setClientInfo","vtp_clientInfo");f("_setDetectFlash","vtp_detectFlash");f("_setDetectTitle","vtp_detectTitle");

void 0!==d.vtp_forceSsl&&d.vtp_forceSsl&&(p.push(["_gat._forceSSL"]),r=!!d.vtp_forceSsl);e("_set","hitCallback",function(){ra(d.vtp_hitCallback)&&d.vtp_hitCallback();d.vtp_gtmOnSuccess()});if("TRACK_EVENT"==d.vtp_trackType){}else if("TRACK_TRANSACTION"==d.vtp_trackType){var C=function(I){return tk("transaction"+I,1)},E=C("Id");e("_addTrans",E,C("Affiliation"),C("Total"),C("Tax"),C("Shipping"));for(var F=C("Products")||[],P=0;P<F.length;P++){var U=F[P];e("_addItem",E,U.sku,U.name,U.category,U.price,U.quantity)}e("_trackTrans");
}else if("LINK"==d.vtp_trackType){}else if("LINK_BY_POST"==d.vtp_trackType){}else if("TRACK_SOCIAL"==d.vtp_trackType){}else if("TRACK_TIMING"==
d.vtp_trackType){}else if("DECORATE_LINK"==d.vtp_trackType){}else if("DECORATE_FORM"==d.vtp_trackType){}else e("_trackPageview");k("_cookiePathCopy",d.vtp_cookiePathCopy);
var O=function(){L("_gat")||d.vtp_gtmOnFailure()};if(d.vtp_doubleClick)b||(b=!0,K(G("https","http","://stats.g.doubleclick.net/dc.js",r),O,d.vtp_gtmOnFailure));else if(!a){var M=d.vtp_useDebugVersion?".google-analytics.com/u/ga_debug.js":".google-analytics.com/ga.js";a=!0;K(G("https://ssl","http://www",M,r),O,d.vtp_gtmOnFailure)}};Z.__ga=c;Z.__ga.g="ga";Z.__ga.h=!0;Z.__ga.b=0}();

Z.a.cegg=["nonGoogleScripts"],function(){var a={};(function(b){Z.__cegg=b;Z.__cegg.g="cegg";Z.__cegg.h=!0;Z.__cegg.b=0})(function(b){try{var c=b.vtp_usersNumericId;if(c)if(a.hasOwnProperty(c)&&!0===a[c])b.vtp_gtmOnSuccess();else{b.vtp_snapshotName&&(u.CE_SNAPSHOT_NAME=b.vtp_snapshotName);for(var d=c.toString();8>d.length;)d="0"+d;var e=d.replace(/(\d+)(\d{4})$/,"/pages/scripts/$1/$2.js");K("//script.crazyegg.com"+e+"?"+Math.floor((new Date).getTime()/36E5),b.vtp_gtmOnSuccess,b.vtp_gtmOnFailure);a[c]=
!0}else D(b.vtp_gtmOnFailure)}catch(f){D(b.vtp_gtmOnFailure)}})}();
Z.a.awct=["google"],function(){var a=!1,b=[],c=function(k){var l=L("google_trackConversion"),m=k.gtm_onFailure;"function"==typeof l?l(k)||m():m()},d=function(){for(;0<b.length;)c(b.shift())},e=function(){return function(){d();a=!1}},f=function(){return function(){d();b={push:c};}},h=function(k){Wf();var l={google_basket_transaction_type:"purchase",google_conversion_domain:"",google_conversion_id:k.vtp_conversionId,google_conversion_label:k.vtp_conversionLabel,
google_conversion_value:k.vtp_conversionValue||0,google_remarketing_only:!1,onload_callback:k.vtp_gtmOnSuccess,gtm_onFailure:k.vtp_gtmOnFailure,google_gtm:yj()},m=function(t){return function(p,r,v){var w="DATA_LAYER"==t?tk(v):k[r];w&&(l[p]=w)}},n=m("JSON");n("google_conversion_currency","vtp_currencyCode");n("google_conversion_order_id","vtp_orderId");k.vtp_enableProductReporting&&(n=m(k.vtp_productReportingDataSource),n("google_conversion_merchant_id","vtp_awMerchantId","aw_merchant_id"),n("google_basket_feed_country",
"vtp_awFeedCountry","aw_feed_country"),n("google_basket_feed_language","vtp_awFeedLanguage","aw_feed_language"),n("google_basket_discount","vtp_discount","discount"),n("google_conversion_items","vtp_items","items"),l.google_conversion_items=l.google_conversion_items.map(function(t){return{value:t.price,quantity:t.quantity,item_id:t.id}}));!k.hasOwnProperty("vtp_enableConversionLinker")||k.vtp_enableConversionLinker?(k.vtp_conversionCookiePrefix&&(l.google_gcl_cookie_prefix=k.vtp_conversionCookiePrefix),
l.google_read_gcl_cookie_opt_out=!1):l.google_read_gcl_cookie_opt_out=!0;var q=!0;q&&b.push(l);a||(a=!0,K("//www.googleadservices.com/pagead/conversion_async.js",f(),e("//www.googleadservices.com/pagead/conversion_async.js")))};Z.__awct=h;Z.__awct.g="awct";Z.__awct.h=!0;Z.__awct.b=0}();

Z.a.baut=["nonGoogleScripts"],function(){var a=!1;(function(b){Z.__baut=b;Z.__baut.g="baut";Z.__baut.h=!0;Z.__baut.b=0})(function(b){var c=b.vtp_uetqName||"uetq",d=L(c,[],!0);if("VARIABLE_REVENUE"==b.vtp_eventType)d.push({gv:b.vtp_goalValue}),b.vtp_gtmOnSuccess();else if("CUSTOM"==b.vtp_eventType){var e={},f=function(h,k){void 0!==b[h]&&(e[k]=b[h])};f("vtp_goalValue","gv");f("vtp_eventCategory","ec");f("vtp_eventAction","ea");f("vtp_eventLabel","el");f("vtp_eventValue","ev");d.push(e);b.vtp_gtmOnSuccess()}else if(a)b.vtp_gtmOnSuccess();
else try{K("//bat.bing.com/bat.js",function(){var h=Lk(L("UET"),{ti:b.vtp_tagId,q:d});u[c]=h;h.push("pageLoad");b.vtp_gtmOnSuccess()},b.vtp_gtmOnFailure),a=!0}catch(h){D(b.vtp_gtmOnFailure)}})}();Z.a.logging=["google"],function(){function a(){return{}}(function(b){Z.__logging=b;Z.__logging.g="logging";Z.__logging.h=!0;Z.__logging.b=0})(function(b){var c=b.vtp_environments||"debug",d=b.vtp_createPermissionError;return{assert:function(e){if("all"!==c&&!Mk.Jg())throw d(e,{},"Logging is not enabled in all environments");},M:a}})}();



Z.a.twitter_website_tag=["nonGoogleScripts"],function(){(function(a){Z.__twitter_website_tag=a;Z.__twitter_website_tag.g="twitter_website_tag";Z.__twitter_website_tag.h=!0;Z.__twitter_website_tag.b=0})(function(a){(function(c,d){c.twq||(d=c.twq=function(){d.exe?d.exe.apply(d,arguments):d.queue.push(arguments)},d.version="1",d.queue=[],K("//static.ads-twitter.com/uwt.js"))})(window,void 0);window.twq("init",String(a.vtp_twitter_pixel_id));var b=Qk(a.vtp_event_parameters,"param_table_key_column","param_table_value_column");
b&&void 0!==b.content_ids&&(b.content_ids=JSON.parse(b.content_ids.replace(/'/g,'"')));window.twq("track",String(a.vtp_event_type),b);D(a.vtp_gtmOnSuccess)})}();

Z.a.html=["customScripts"],function(){function a(d,e,f,h){return function(){try{if(0<e.length){var k=e.shift(),l=a(d,e,f,h);if("SCRIPT"==String(k.nodeName).toUpperCase()&&"text/gtmscript"==k.type){var m=A.createElement("script");m.async=!1;m.type="text/javascript";m.id=k.id;m.text=k.text||k.textContent||k.innerHTML||"";k.charset&&(m.charset=k.charset);var n=k.getAttribute("data-gtmsrc");n&&(m.src=n,mc(m,l));d.insertBefore(m,null);n||l()}else if(k.innerHTML&&0<=k.innerHTML.toLowerCase().indexOf("<script")){for(var q=
[];k.firstChild;)q.push(k.removeChild(k.firstChild));d.insertBefore(k,null);a(k,q,l,h)()}else d.insertBefore(k,null),l()}else f()}catch(t){D(h)}}}var c=function(d){if(A.body){var e=
d.vtp_gtmOnFailure,f=Gk(d.vtp_html,d.vtp_gtmOnSuccess,e),h=f.Vc,k=f.R;if(d.vtp_useIframe){}else d.vtp_supportDocumentWrite?b(h,k,e):a(A.body,vc(h),k,e)()}else nk(function(){c(d)},
200)};Z.__html=c;Z.__html.g="html";Z.__html.h=!0;Z.__html.b=0}();



var im={};im.macro=function(a){if(hi.Ic.hasOwnProperty(a))return hi.Ic[a]},im.onHtmlSuccess=hi.ce(!0),im.onHtmlFailure=hi.ce(!1);im.dataLayer=qf;im.callback=function(a){Je.hasOwnProperty(a)&&ra(Je[a])&&Je[a]();delete Je[a]};im.Nf=function(){Ae[ze.o]=im;La(Ke,Z.a);Vd=Vd||hi;Wd=Ff};
im.Dg=function(){bj.gtm_3pds=!0;Ae=u.google_tag_manager=u.google_tag_manager||{};if(Ae[ze.o]){var a=Ae.zones;a&&a.unregisterChild(ze.o)}else{for(var b=data.resource||{},c=b.macros||[],d=0;d<c.length;d++)Od.push(c[d]);for(var e=b.tags||[],f=0;f<e.length;f++)Rd.push(e[f]);for(var h=b.predicates||[],
k=0;k<h.length;k++)Qd.push(h[k]);for(var l=b.rules||[],m=0;m<l.length;m++){for(var n=l[m],q={},t=0;t<n.length;t++)q[n[t][0]]=Array.prototype.slice.call(n[t],1);Pd.push(q)}Td=Z;Ud=Jk;var p=data.permissions||{},r=data.sandboxed_scripts;fh();lh(p);if(void 0!==r)for(var v=["sandboxedScripts"],w=0;w<r.length;w++){var y=r[w].replace(/^_*/,"");Ke[y]=v}im.Nf();Kh();If=!1;Jf=0;if("interactive"==A.readyState&&!A.createEventObject||"complete"==A.readyState)Lf();else{rc(A,"DOMContentLoaded",Lf);rc(A,"readystatechange",
Lf);if(A.createEventObject&&A.documentElement.doScroll){var x=!0;try{x=!u.frameElement}catch(E){}x&&Mf()}rc(u,"load",Lf)}yh=!1;"complete"===A.readyState?Ah():rc(u,"load",Ah);a:{if(!df)break a;u.setInterval(ef,864E5);}
Ge=(new Date).getTime();}};(0,im.Dg)();

})()
